'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const colors=['#67f2dd','#ff9d6c'];
let width=1000,height=540,scale=1,players=[],mode='cpu',state='ready',remaining=60,last=0,accumulator=0,elapsed=0,particles=[],rings=[],shake=0,sound=false,audioCtx=null;
const inputs=[{swing:false,lock:false},{swing:false,lock:false}];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function resize(){const rect=canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);width=rect.width<650?700:1000;height=width*rect.height/rect.width;scale=canvas.width/width;resetPhysics();}
function makePlayer(i){const x=width*(i===0?.37:.63),y=height*.48,L=width*.087;const p={i,x,y,L,hp:100,cool:0,locked:0,heldLast:false,hitCool:0,trail:[],chords:[],nodes:[{x,y,px:x,py:y}]};for(let j=1;j<=3;j++){const angle=(i===0?-.8:.8)+(j-1)*.45;p.nodes.push({x:p.nodes[j-1].x+Math.sin(angle)*L,y:p.nodes[j-1].y+Math.cos(angle)*L,px:0,py:0});p.nodes[j].px=p.nodes[j].x;p.nodes[j].py=p.nodes[j].y;}return p;}
function resetPhysics(){const old=players;players=[makePlayer(0),makePlayer(1)];players.forEach((p,i)=>{p.hp=old[i]?.hp??100;});particles=[];rings=[];}
function clearInput(){inputs.forEach(p=>{p.swing=false;p.lock=false;});document.querySelectorAll('.held').forEach(e=>e.classList.remove('held'));}
function tone(freq,dur=.07,type='sine',gain=.04){if(!sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.45,audioCtx.currentTime+dur);g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur);}catch{}}
function lock(p){p.locked=.7;p.cool=2.8;p.chords=[[0,2],[1,3],[0,3]].map(([a,b])=>({a,b,d:Math.hypot(p.nodes[a].x-p.nodes[b].x,p.nodes[a].y-p.nodes[b].y)}));tone(430,.05);}
function constrain(p,a,b,d){const n=p.nodes[a],m=p.nodes[b],dx=m.x-n.x,dy=m.y-n.y,dist=Math.hypot(dx,dy)||.001;const err=(dist-d)/dist,w=a===0?1:.5;if(a!==0){n.x+=dx*err*.5;n.y+=dy*err*.5;}m.x-=dx*err*w;m.y-=dy*err*w;}
function step(dt,active){elapsed+=dt;
 if(active){remaining=Math.max(0,remaining-dt);if(mode==='cpu'){const p=players[1],tip=players[0].nodes[3];inputs[1].swing=Math.sin(elapsed*2.7)>.0||Math.sin(elapsed*.63)>.6;inputs[1].lock=p.locked>0||(Math.hypot(tip.x-p.x,tip.y-p.y)<p.L*1.5&&p.cool<=0);}}
 for(const p of players){p.cool=Math.max(0,p.cool-dt);p.hitCool=Math.max(0,p.hitCool-dt);const input=active?inputs[p.i]:{swing:true,lock:false};if(active&&input.lock&&!p.heldLast&&p.cool===0)lock(p);p.heldLast=input.lock;p.locked=Math.max(0,p.locked-dt);if(!input.lock)p.locked=0;
 const n=p.nodes[1],dx=n.x-p.x,dy=n.y-p.y,len=Math.hypot(dx,dy)||1,dir=p.i===0?-1:1;
 const previous={x:p.nodes[3].x,y:p.nodes[3].y};
 for(let j=1;j<4;j++){const b=p.nodes[j],vx=clamp((b.x-b.px)*.9988,-width*.035,width*.035),vy=clamp((b.y-b.py)*.9988,-width*.035,width*.035);b.px=b.x;b.py=b.y;let ax=0,ay=width*.6;if(j===1&&input.swing){ax=-dy/len*width*4.8*dir;ay+=dx/len*width*4.8*dir;}b.x+=vx+ax*dt*dt;b.y+=vy+ay*dt*dt;}
 for(let iteration=0;iteration<10;iteration++){for(let j=0;j<3;j++)constrain(p,j,j+1,p.L);if(p.locked>0)for(const c of p.chords)constrain(p,c.a,c.b,c.d);}
 const tip=p.nodes[3];if(active){const enemy=players[1-p.i],ex=enemy.x,ey=enemy.y,tx=tip.x-previous.x,ty=tip.y-previous.y,t=clamp(((ex-previous.x)*tx+(ey-previous.y)*ty)/(tx*tx+ty*ty||1),0,1),distance=Math.hypot(previous.x+tx*t-ex,previous.y+ty*t-ey),speed=Math.hypot(tx,ty)/dt;
 if(distance<width*.038&&speed>width*.16&&p.hitCool===0&&enemy.hp>0){const damage=Math.round(clamp(speed/width*12,7,25)*(enemy.locked>0?.35:1));enemy.hp=Math.max(0,enemy.hp-damage);p.hitCool=.48;shake=5;burst(ex,ey,colors[p.i],damage,enemy.locked>0);tone(95+damage*3,.14,'triangle',.09);tip.px=tip.x+tx*.65;tip.py=tip.y+ty*.65;}}
 }
 if(active&&(players.some(p=>p.hp<=0)||remaining<=0))finish();
}
function burst(x,y,color,damage,guard){for(let i=0;i<22;i++){const a=Math.random()*Math.PI*2,v=50+Math.random()*260;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.5+Math.random()*.3,color});}rings.push({x,y,life:.55,color,text:guard?'GUARD −'+damage:'−'+damage});}
function updateUI(){$('time').textContent=String(Math.ceil(remaining)).padStart(2,'0');players.forEach((p,i)=>{$('hp'+i).textContent=p.hp;$('bar'+i).style.width=p.hp+'%';$('cool'+i).textContent=p.locked>0?'固定中':p.cool>0?p.cool.toFixed(1)+'秒':'長押し / '+(i===0?'S':'L');$('lock'+i).classList.toggle('held',p.locked>0);});}
function draw(dt){ctx.setTransform(scale,0,0,scale,0,0);ctx.clearRect(0,0,width,height);ctx.fillStyle='#0c1421';ctx.fillRect(0,0,width,height);ctx.save();if(shake>0){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.84;}ctx.strokeStyle='#192536';ctx.lineWidth=.6;for(let x=0;x<width;x+=width/25){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,height);ctx.stroke();}for(let y=height*.48%40;y<height;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(width,y);ctx.stroke();}ctx.setLineDash([4,8]);ctx.strokeStyle='#304055';ctx.beginPath();ctx.moveTo(width/2,35);ctx.lineTo(width/2,height-35);ctx.stroke();ctx.setLineDash([]);
 for(const p of players){const c=colors[p.i],tip=p.nodes[3];if(state==='running'||state==='ready'){p.trail.push({x:tip.x,y:tip.y});if(p.trail.length>45)p.trail.shift();}ctx.strokeStyle=c;ctx.lineWidth=2;for(let j=1;j<p.trail.length;j++){ctx.globalAlpha=j/p.trail.length*.28;ctx.beginPath();ctx.moveTo(p.trail[j-1].x,p.trail[j-1].y);ctx.lineTo(p.trail[j].x,p.trail[j].y);ctx.stroke();}ctx.globalAlpha=1;
 ctx.strokeStyle=c+'19';ctx.lineWidth=1;ctx.beginPath();ctx.arc(p.x,p.y,p.L*2.7,0,Math.PI*2);ctx.stroke();ctx.fillStyle=c+'09';ctx.beginPath();ctx.arc(p.x,p.y,width*.051,0,Math.PI*2);ctx.fill();ctx.strokeStyle=c;ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,width*.026,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#0c1421';ctx.fill();ctx.fillStyle=c;ctx.font='bold '+width*.016+'px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('0'+(p.i+1),p.x,p.y);
 if(p.locked>0){ctx.strokeStyle=c;ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,width*.036,-Math.PI/2,-Math.PI/2+Math.PI*2*p.locked/.7);ctx.stroke();}
 ctx.lineCap='round';for(let j=1;j<4;j++){const a=p.nodes[j-1],b=p.nodes[j];ctx.strokeStyle=p.locked>0?'#eefcf7':c;ctx.lineWidth=j===3?5:7;ctx.shadowBlur=p.locked>0?12:0;ctx.shadowColor=c;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#0c1421';ctx.strokeStyle=c;ctx.lineWidth=2;ctx.beginPath();ctx.arc(b.x,b.y,j===3?width*.014:width*.0065,0,Math.PI*2);ctx.fill();ctx.stroke();if(j===3){ctx.shadowBlur=20;ctx.shadowColor=c;ctx.fillStyle=c;ctx.beginPath();ctx.arc(b.x,b.y,width*.008,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;}}
 }
 for(const p of particles){if(state!=='paused'){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;}ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,3,3);}particles=particles.filter(p=>p.life>0);ctx.globalAlpha=1;
 for(const r of rings){if(state!=='paused')r.life-=dt;ctx.globalAlpha=Math.max(0,r.life/.55);ctx.strokeStyle=r.color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(r.x,r.y,(.55-r.life)*160+20,0,Math.PI*2);ctx.stroke();ctx.fillStyle=r.color;ctx.font='bold 25px Arial';ctx.fillText(r.text,r.x,r.y-50-(.55-r.life)*50);}rings=rings.filter(r=>r.life>0);ctx.globalAlpha=1;ctx.restore();}
function frame(now){const dt=Math.min((now-last)/1000||0,.04);last=now;if(state==='running'||state==='ready'){accumulator+=dt;while(accumulator>=1/240){step(1/240,state==='running');accumulator-=1/240;if(state==='over')break;}}draw(dt);updateUI();requestAnimationFrame(frame);}
function start(){clearInput();remaining=60;elapsed=0;accumulator=0;players=[];resetPhysics();state='running';$('overlay').classList.add('hidden');$('pause').disabled=false;$('pause').textContent='一時停止';$('name1').textContent=mode==='cpu'?'02 / CPU':'02 / PLAYER';$('side1').innerHTML=mode==='cpu'?'CPU <span>自動操作</span>':'PLAYER 02 <span>K / L</span>';['swing1','lock1'].forEach(id=>$(id).disabled=mode==='cpu');tone(660,.12);}
function showCard(title,sub,button){$('overlay').classList.remove('hidden');$('overlay').innerHTML='<div class="start-card"><div class="eyebrow">TRIPLE PENDULUM DUEL</div><h1>'+title+'</h1><p>'+sub+'</p><button id="resume" class="primary">'+button+' <span>↗</span></button><button id="menu" style="margin-top:12px;padding:10px 20px;font-size:14px">モードを選び直す</button></div>';$('menu').onclick=menu;}
const originalOverlay=$('overlay').innerHTML;
function bindMenu(){$('cpu').onclick=()=>selectMode('cpu');$('local').onclick=()=>selectMode('local');$('start').onclick=start;selectMode(mode);}
function selectMode(m){mode=m;['cpu','local'].forEach(id=>{$(id).classList.toggle('selected',id===m);$(id).setAttribute('aria-pressed',String(id===m));});}
function menu(){state='ready';remaining=60;clearInput();players=[];resetPhysics();$('pause').disabled=true;$('pause').textContent='一時停止';$('overlay').innerHTML=originalOverlay;bindMenu();}
function finish(){state='over';clearInput();$('pause').disabled=true;const a=players[0].hp,b=players[1].hp;showCard(a===b?'DRAW':a>b?'PLAYER 01 <em>WIN</em>':(mode==='cpu'?'CPU':'PLAYER 02')+' <em>WIN</em>','残りHP '+a+' : '+b+' · '+(remaining<=0?'タイムアップ':'KNOCKOUT'),'もう一度対戦');$('resume').onclick=start;tone(a>b?880:220,.3);}
function pause(){if(state==='running'){state='paused';clearInput();$('pause').textContent='再開';showCard('PAUSED','一息ついて、次の一振りを。','対戦に戻る');$('resume').onclick=pause;}else if(state==='paused'){state='running';accumulator=0;$('overlay').classList.add('hidden');$('pause').textContent='一時停止';}}
$('pause').onclick=pause;$('sound').onclick=()=>{sound=!sound;$('sound').textContent='音 '+(sound?'ON':'OFF');$('sound').setAttribute('aria-label','効果音を'+(sound?'オフ':'オン')+'にする');if(sound)tone(520);};
for(let i=0;i<2;i++)for(const action of ['swing','lock']){
 const b=$(action+i);
 const release=e=>{e.preventDefault();inputs[i][action]=false;b.classList.remove('held');};
 b.addEventListener('pointerdown',e=>{e.preventDefault();if((e.pointerType==='mouse'&&e.button!==0)||state!=='running'||(i===1&&mode==='cpu'))return;if(b.setPointerCapture)try{b.setPointerCapture(e.pointerId);}catch{}inputs[i][action]=true;b.classList.add('held');},{passive:false});
 b.addEventListener('pointerup',release,{passive:false});
 b.addEventListener('pointercancel',release,{passive:false});
 b.addEventListener('lostpointercapture',()=>{inputs[i][action]=false;b.classList.remove('held');});
 b.addEventListener('contextmenu',e=>e.preventDefault());
}
const controls=document.querySelector('.controls');
controls.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});
controls.addEventListener('dblclick',e=>e.preventDefault(),{passive:false});
const keys={a:[0,'swing'],s:[0,'lock'],k:[1,'swing'],l:[1,'lock']};window.addEventListener('keydown',e=>{if(e.key==='Escape'&&!e.repeat){pause();return;}const k=keys[e.key.toLowerCase()];if(!k||state!=='running'||(k[0]===1&&mode==='cpu'))return;e.preventDefault();inputs[k[0]][k[1]]=true;$(k[1]+k[0]).classList.add('held');});window.addEventListener('keyup',e=>{const k=keys[e.key.toLowerCase()];if(!k)return;inputs[k[0]][k[1]]=false;$(k[1]+k[0]).classList.remove('held');});window.addEventListener('blur',()=>{clearInput();if(state==='running')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='running')pause();});window.addEventListener('resize',()=>{if(state==='running')pause();resize();});bindMenu();resize();requestAnimationFrame(frame);
