'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const colors=['#67f2dd','#ff9d6c'];
let width=1000,height=540,scale=1,players=[],mode='cpu',state='ready',remaining=60,last=0,accumulator=0,elapsed=0,particles=[],rings=[],shake=0,sound=false,audioCtx=null,countdown=0,countdownCue='';
const inputs=[{ccw:false,lock:false,cw:false},{ccw:false,lock:false,cw:false}];
const weaponChoices=['balanced','balanced'],readySelections=[false,false];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function resize(){const rect=canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);width=rect.width<650?700:1000;height=width*rect.height/rect.width;scale=canvas.width/width;resetPhysics();}
function makePlayer(i){const weapon=WEAPONS[weaponChoices[i]]||WEAPONS.balanced,x=width*(i===0?.37:.63),y=height*.48,L=width*.087*weapon.segmentLength;const p={i,x,y,L,weapon,hp:100,cool:0,locked:0,heldLast:false,hitCool:0,trail:[],chords:[],aiDirection:i===0?-1:1,aiTimer:0,nodes:[{x,y,px:x,py:y}]};for(let j=1;j<=weapon.segments;j++){const angle=(i===0?-.8:.8)+(j-1)*.45;p.nodes.push({x:p.nodes[j-1].x+Math.sin(angle)*L,y:p.nodes[j-1].y+Math.cos(angle)*L,px:0,py:0});p.nodes[j].px=p.nodes[j].x;p.nodes[j].py=p.nodes[j].y;}return p;}
function resetPhysics(){const old=players;players=[makePlayer(0),makePlayer(1)];players.forEach((p,i)=>{p.hp=old[i]?.hp??100;});particles=[];rings=[];}
function clearInput(){inputs.forEach(p=>{p.ccw=false;p.lock=false;p.cw=false;});document.querySelectorAll('.held').forEach(e=>e.classList.remove('held'));}
function tone(freq,dur=.07,type='sine',gain=.04){if(!sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.45,audioCtx.currentTime+dur);g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur);}catch{}}
function lock(p){p.locked=.7;p.cool=2.8;const pairs=[];for(let a=0;a<p.nodes.length-2;a++)pairs.push([a,a+2]);if(p.nodes.length>3)pairs.push([0,p.nodes.length-1]);p.chords=pairs.map(([a,b])=>({a,b,d:Math.hypot(p.nodes[a].x-p.nodes[b].x,p.nodes[a].y-p.nodes[b].y)}));tone(430,.05);}
function constrain(p,a,b,d){const n=p.nodes[a],m=p.nodes[b],dx=m.x-n.x,dy=m.y-n.y,dist=Math.hypot(dx,dy)||.001;const err=(dist-d)/dist,w=a===0?1:.5;if(a!==0){n.x+=dx*err*.5;n.y+=dy*err*.5;}m.x-=dx*err*w;m.y-=dy*err*w;}
function updateCpu(dt){const p=players[1],enemy=players[0],tip=p.nodes[p.nodes.length-1],enemyTip=enemy.nodes[enemy.nodes.length-1];p.aiTimer-=dt;if(p.aiTimer<=0){const radialX=p.nodes[1].x-p.x,radialY=p.nodes[1].y-p.y,targetX=enemy.x-tip.x,targetY=enemy.y-tip.y,cross=radialX*targetY-radialY*targetX;p.aiDirection=cross>=0?1:-1;if(Math.random()<.24)p.aiDirection*=-1;p.aiTimer=.65+Math.random()*.8;}inputs[1].cw=p.aiDirection>0;inputs[1].ccw=p.aiDirection<0;inputs[1].lock=p.locked>0||(Math.hypot(enemyTip.x-p.x,enemyTip.y-p.y)<p.L*1.6&&p.cool<=0);}
function step(dt,active){elapsed+=dt;
 if(active){remaining=Math.max(0,remaining-dt);if(mode==='cpu')updateCpu(dt);}
 for(const p of players){p.cool=Math.max(0,p.cool-dt);p.hitCool=Math.max(0,p.hitCool-dt);const input=active?inputs[p.i]:(p.i===0?{ccw:true,cw:false,lock:false}:{ccw:false,cw:true,lock:false});if(active&&input.lock&&!p.heldLast&&p.cool===0)lock(p);p.heldLast=input.lock;p.locked=Math.max(0,p.locked-dt);if(!input.lock)p.locked=0;
 const n=p.nodes[1],dx=n.x-p.x,dy=n.y-p.y,len=Math.hypot(dx,dy)||1,turn=(input.cw?1:0)-(input.ccw?1:0),tipIndex=p.nodes.length-1;
 const previous={x:p.nodes[tipIndex].x,y:p.nodes[tipIndex].y};
 for(let j=1;j<p.nodes.length;j++){const b=p.nodes[j],mass=j===tipIndex?p.weapon.tipMass:p.weapon.segmentMass,damping=1-(1-p.weapon.damping)/Math.max(.5,mass),vx=clamp((b.x-b.px)*damping,-width*.035,width*.035),vy=clamp((b.y-b.py)*damping,-width*.035,width*.035);b.px=b.x;b.py=b.y;let ax=0,ay=width*.6*p.weapon.gravity*(j===tipIndex?Math.sqrt(p.weapon.tipMass):1);if(j===1&&turn){const torque=width*4.8*p.weapon.motorPower*turn;ax=-dy/len*torque;ay+=dx/len*torque;}b.x+=vx+ax*dt*dt;b.y+=vy+ay*dt*dt;}
 for(let iteration=0;iteration<10;iteration++){for(let j=0;j<p.nodes.length-1;j++)constrain(p,j,j+1,p.L);if(p.locked>0)for(const c of p.chords)constrain(p,c.a,c.b,c.d);}
 const tip=p.nodes[tipIndex];if(active){const enemy=players[1-p.i],ex=enemy.x,ey=enemy.y,tx=tip.x-previous.x,ty=tip.y-previous.y,t=clamp(((ex-previous.x)*tx+(ey-previous.y)*ty)/(tx*tx+ty*ty||1),0,1),distance=Math.hypot(previous.x+tx*t-ex,previous.y+ty*t-ey),speed=Math.hypot(tx,ty)/dt;
 if(distance<width*.038&&speed>width*.16&&p.hitCool===0&&enemy.hp>0){const baseDamage=clamp(speed/width*12,7,25),damage=Math.max(1,Math.round(baseDamage*p.weapon.damageMultiplier*(enemy.locked>0?.35:1)));enemy.hp=Math.max(0,enemy.hp-damage);p.hitCool=.48;shake=5;burst(ex,ey,colors[p.i],damage,enemy.locked>0);tone(95+damage*3,.14,'triangle',.09);tip.px=tip.x+tx*.65/p.weapon.tipMass;tip.py=tip.y+ty*.65/p.weapon.tipMass;}}
 }
 if(active&&(players.some(p=>p.hp<=0)||remaining<=0))finish();
}
function burst(x,y,color,damage,guard){for(let i=0;i<22;i++){const a=Math.random()*Math.PI*2,v=50+Math.random()*260;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.5+Math.random()*.3,color});}rings.push({x,y,life:.55,color,text:guard?'GUARD −'+damage:'−'+damage});}
function updateUI(){$('time').textContent=String(Math.ceil(remaining)).padStart(2,'0');players.forEach((p,i)=>{$('hp'+i).textContent=p.hp;$('bar'+i).style.width=p.hp+'%';$('weapon'+i).textContent=p.weapon.name;$('cool'+i).textContent=p.locked>0?'固定中':p.cool>0?p.cool.toFixed(1)+'秒':(i===0?'S':'K');$('lock'+i).classList.toggle('held',p.locked>0);});}
function draw(dt){ctx.setTransform(scale,0,0,scale,0,0);ctx.clearRect(0,0,width,height);ctx.fillStyle='#0c1421';ctx.fillRect(0,0,width,height);ctx.save();if(shake>0){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.84;}ctx.strokeStyle='#192536';ctx.lineWidth=.6;for(let x=0;x<width;x+=width/25){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,height);ctx.stroke();}for(let y=height*.48%40;y<height;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(width,y);ctx.stroke();}ctx.setLineDash([4,8]);ctx.strokeStyle='#304055';ctx.beginPath();ctx.moveTo(width/2,35);ctx.lineTo(width/2,height-35);ctx.stroke();ctx.setLineDash([]);
 for(const p of players){const c=colors[p.i],tipIndex=p.nodes.length-1,tip=p.nodes[tipIndex];if(['running','ready','selecting','countdown'].includes(state)){p.trail.push({x:tip.x,y:tip.y});if(p.trail.length>45)p.trail.shift();}ctx.strokeStyle=c;ctx.lineWidth=2;for(let j=1;j<p.trail.length;j++){ctx.globalAlpha=j/p.trail.length*.28;ctx.beginPath();ctx.moveTo(p.trail[j-1].x,p.trail[j-1].y);ctx.lineTo(p.trail[j].x,p.trail[j].y);ctx.stroke();}ctx.globalAlpha=1;
 ctx.strokeStyle=c+'19';ctx.lineWidth=1;ctx.beginPath();ctx.arc(p.x,p.y,p.L*p.weapon.segments*.9,0,Math.PI*2);ctx.stroke();ctx.fillStyle=c+'09';ctx.beginPath();ctx.arc(p.x,p.y,width*.051,0,Math.PI*2);ctx.fill();ctx.strokeStyle=c;ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,width*.026,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#0c1421';ctx.fill();ctx.fillStyle=c;ctx.font='bold '+width*.016+'px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('0'+(p.i+1),p.x,p.y);
 if(p.locked>0){ctx.strokeStyle=c;ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,width*.036,-Math.PI/2,-Math.PI/2+Math.PI*2*p.locked/.7);ctx.stroke();}
 ctx.lineCap='round';for(let j=1;j<p.nodes.length;j++){const a=p.nodes[j-1],b=p.nodes[j],isTip=j===tipIndex;ctx.strokeStyle=p.locked>0?'#eefcf7':c;ctx.lineWidth=(isTip?5:7)*p.weapon.rodWidth;ctx.shadowBlur=p.locked>0?12:0;ctx.shadowColor=c;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#0c1421';ctx.strokeStyle=c;ctx.lineWidth=2;ctx.beginPath();ctx.arc(b.x,b.y,isTip?width*.014*p.weapon.tipSize:width*.0065*p.weapon.rodWidth,0,Math.PI*2);ctx.fill();ctx.stroke();if(isTip){ctx.shadowBlur=20;ctx.shadowColor=c;ctx.fillStyle=c;ctx.beginPath();ctx.arc(b.x,b.y,width*.008*p.weapon.tipSize,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;}}
 }
 for(const p of particles){if(state!=='paused'){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;}ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,3,3);}particles=particles.filter(p=>p.life>0);ctx.globalAlpha=1;
 for(const r of rings){if(state!=='paused')r.life-=dt;ctx.globalAlpha=Math.max(0,r.life/.55);ctx.strokeStyle=r.color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(r.x,r.y,(.55-r.life)*160+20,0,Math.PI*2);ctx.stroke();ctx.fillStyle=r.color;ctx.font='bold 25px Arial';ctx.fillText(r.text,r.x,r.y-50-(.55-r.life)*50);}rings=rings.filter(r=>r.life>0);ctx.globalAlpha=1;ctx.restore();}
function updateCountdown(dt){countdown-=dt;const cue=countdown>.65?String(Math.max(1,Math.ceil(countdown-.65))):'FIGHT';if(cue!==countdownCue){countdownCue=cue;$('countdownNumber').textContent=cue;tone(cue==='FIGHT'?720:420,.08);}if(countdown<=0)startBattle();}
function frame(now){const dt=Math.min((now-last)/1000||0,.04);last=now;if(state==='countdown')updateCountdown(dt);if(['running','ready','selecting','countdown'].includes(state)){accumulator+=dt;while(accumulator>=1/240){step(1/240,state==='running');accumulator-=1/240;if(state==='over')break;}}draw(dt);updateUI();requestAnimationFrame(frame);}
function stars(value){return '★'.repeat(value)+'☆'.repeat(5-value);}
function weaponStats(weapon){return '<dl class="weapon-stats"><dt>POWER</dt><dd>'+stars(weapon.stats.power)+'</dd><dt>SPEED</dt><dd>'+stars(weapon.stats.speed)+'</dd><dt>REACH</dt><dd>'+stars(weapon.stats.reach)+'</dd><dt>CONTROL</dt><dd>'+stars(weapon.stats.control)+'</dd></dl>';}
function weaponPanel(i){const isCpu=mode==='cpu'&&i===1,weapon=WEAPONS[weaponChoices[i]],ready=readySelections[i],accent=i===0?'cyan':'orange';if(isCpu)return '<section class="weapon-panel '+accent+'"><span class="weapon-owner">02 / CPU</span><div class="weapon-name"><strong>RANDOM</strong><small>READY時に武器を決定</small></div><div class="weapon-preview balanced" style="--preview-speed:1;--tip-size:1"><i class="preview-chain"></i><b class="preview-tip"></b></div><dl class="weapon-stats"><dt>POWER</dt><dd>？？？？？</dd><dt>SPEED</dt><dd>？？？？？</dd><dt>REACH</dt><dd>？？？？？</dd><dt>CONTROL</dt><dd>？？？？？</dd></dl><button class="weapon-ready" type="button" disabled>CPU AUTO</button></section>';return '<section class="weapon-panel '+accent+(ready?' is-ready':'')+'"><span class="weapon-owner">PLAYER 0'+(i+1)+'</span><div class="weapon-switcher"><button class="weapon-arrow" type="button" data-player="'+i+'" data-direction="-1" aria-label="前の武器" '+(ready?'disabled':'')+'>‹</button><div class="weapon-name"><strong>'+weapon.name+'</strong><small>'+weapon.description+'</small></div><button class="weapon-arrow" type="button" data-player="'+i+'" data-direction="1" aria-label="次の武器" '+(ready?'disabled':'')+'>›</button></div><div class="weapon-preview '+weapon.id+'" style="--preview-speed:'+weapon.previewSpeed+';--tip-size:'+weapon.tipSize+'"><i class="preview-chain"></i><b class="preview-tip"></b></div>'+weaponStats(weapon)+'<button class="weapon-ready" type="button" data-ready="'+i+'">'+(ready?'READY ✓':'READY')+'</button></section>';}
function renderWeaponSelect(){state='selecting';$('overlay').classList.remove('hidden');$('overlay').innerHTML='<div class="weapon-card"><div class="eyebrow">SELECT YOUR PENDULUM</div><h2>武器を選択</h2><div class="weapon-select-grid">'+weaponPanel(0)+weaponPanel(1)+'</div><button id="weaponBack" class="weapon-back" type="button">モード選択へ戻る</button></div>';document.querySelectorAll('.weapon-arrow').forEach(button=>button.onclick=()=>cycleWeapon(Number(button.dataset.player),Number(button.dataset.direction)));document.querySelectorAll('[data-ready]').forEach(button=>button.onclick=()=>readyWeapon(Number(button.dataset.ready)));$('weaponBack').onclick=menu;}
function openWeaponSelect(){clearInput();readySelections[0]=false;readySelections[1]=false;$('pause').disabled=true;renderWeaponSelect();}
function cycleWeapon(i,direction){if(readySelections[i]||(mode==='cpu'&&i===1))return;const current=WEAPON_IDS.indexOf(weaponChoices[i]);weaponChoices[i]=WEAPON_IDS[(current+direction+WEAPON_IDS.length)%WEAPON_IDS.length];resetPhysics();renderWeaponSelect();tone(510,.04);}
function readyWeapon(i){if(readySelections[i]){readySelections[i]=false;renderWeaponSelect();return;}readySelections[i]=true;tone(620,.07);if(mode==='cpu'&&i===0){weaponChoices[1]=WEAPON_IDS[Math.floor(Math.random()*WEAPON_IDS.length)];readySelections[1]=true;beginCountdown();return;}if(readySelections[0]&&readySelections[1])beginCountdown();else renderWeaponSelect();}
function configureMatchUI(){$('name1').textContent=mode==='cpu'?'02 / CPU':'02 / PLAYER';$('side1').innerHTML=mode==='cpu'?'CPU <span>自動操作</span>':'PLAYER 02 <span>J ↺ / K LOCK / L ↻</span>';['ccw1','lock1','cw1'].forEach(id=>$(id).disabled=mode==='cpu');}
function beginCountdown(){clearInput();remaining=60;elapsed=0;accumulator=0;players=[];resetPhysics();configureMatchUI();state='countdown';countdown=3.65;countdownCue='3';$('pause').disabled=true;$('overlay').classList.remove('hidden');$('overlay').innerHTML='<div class="countdown-card"><div class="eyebrow">READY</div><div class="countdown-match"><span style="color:'+colors[0]+'">'+WEAPONS[weaponChoices[0]].name+'</span> VS <span style="color:'+colors[1]+'">'+WEAPONS[weaponChoices[1]].name+'</span></div><div id="countdownNumber" class="countdown-number">3</div></div>';tone(420,.08);}
function startBattle(){state='running';countdown=0;accumulator=0;$('overlay').classList.add('hidden');$('pause').disabled=false;$('pause').textContent='一時停止';tone(720,.12);}
function start(){openWeaponSelect();}
function showCard(title,sub,button){$('overlay').classList.remove('hidden');$('overlay').innerHTML='<div class="start-card"><div class="eyebrow">TRIPLE PENDULUM DUEL</div><h1>'+title+'</h1><p>'+sub+'</p><button id="resume" class="primary">'+button+' <span>↗</span></button><button id="menu" style="margin-top:12px;padding:10px 20px;font-size:14px">モードを選び直す</button></div>';$('menu').onclick=menu;}
const originalOverlay=$('overlay').innerHTML;
function bindMenu(){$('cpu').onclick=()=>selectMode('cpu');$('local').onclick=()=>selectMode('local');$('start').onclick=openWeaponSelect;selectMode(mode);}
function selectMode(m){mode=m;['cpu','local'].forEach(id=>{$(id).classList.toggle('selected',id===m);$(id).setAttribute('aria-pressed',String(id===m));});}
function menu(){state='ready';remaining=60;clearInput();readySelections[0]=false;readySelections[1]=false;players=[];resetPhysics();$('pause').disabled=true;$('pause').textContent='一時停止';$('overlay').innerHTML=originalOverlay;bindMenu();}
function finish(){state='over';clearInput();$('pause').disabled=true;const a=players[0].hp,b=players[1].hp,title=a===b?'DRAW':a>b?'PLAYER 01 <em>WIN</em>':(mode==='cpu'?'CPU':'PLAYER 02')+' <em>WIN</em>';$('overlay').classList.remove('hidden');$('overlay').innerHTML='<div class="start-card"><div class="eyebrow">TRIPLE PENDULUM DUEL</div><h1>'+title+'</h1><p>残りHP '+a+' : '+b+' · '+(remaining<=0?'タイムアップ':'KNOCKOUT')+'</p><button id="resume" class="primary" type="button">同じ武器でもう一度 <span>↗</span></button><button id="weapons" style="margin-top:12px;padding:10px 20px;font-size:14px" type="button">武器を選び直す</button><button id="menu" style="margin-top:12px;padding:10px 20px;font-size:14px" type="button">モードを選び直す</button></div>';$('resume').onclick=beginCountdown;$('weapons').onclick=openWeaponSelect;$('menu').onclick=menu;tone(a>b?880:220,.3);}
function pause(){if(state==='running'){state='paused';clearInput();$('pause').textContent='再開';showCard('PAUSED','一息ついて、次の一振りを。','対戦に戻る');$('resume').onclick=pause;}else if(state==='paused'){state='running';accumulator=0;$('overlay').classList.add('hidden');$('pause').textContent='一時停止';}}
$('pause').onclick=pause;$('sound').onclick=()=>{sound=!sound;$('sound').textContent='音 '+(sound?'ON':'OFF');$('sound').setAttribute('aria-label','効果音を'+(sound?'オフ':'オン')+'にする');if(sound)tone(520);};
for(let i=0;i<2;i++)for(const action of ['ccw','lock','cw']){
 const b=$(action+i);
 const release=e=>{e.preventDefault();inputs[i][action]=false;b.classList.remove('held');};
 b.addEventListener('pointerdown',e=>{e.preventDefault();if((e.pointerType==='mouse'&&e.button!==0)||state!=='running'||(i===1&&mode==='cpu'))return;if(b.setPointerCapture)try{b.setPointerCapture(e.pointerId);}catch{}inputs[i][action]=true;b.classList.add('held');},{passive:false});
 b.addEventListener('pointerup',release,{passive:false});
 b.addEventListener('pointercancel',release,{passive:false});
 b.addEventListener('lostpointercapture',()=>{inputs[i][action]=false;b.classList.remove('held');});
 b.addEventListener('contextmenu',e=>e.preventDefault());
}
const controls=document.querySelector('.controls');
controls.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});
controls.addEventListener('dblclick',e=>e.preventDefault(),{passive:false});
const keys={a:[0,'ccw'],s:[0,'lock'],d:[0,'cw'],j:[1,'ccw'],k:[1,'lock'],l:[1,'cw']};
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&!e.repeat){pause();return;}const key=keys[e.key.toLowerCase()];if(!key||state!=='running'||(key[0]===1&&mode==='cpu'))return;e.preventDefault();inputs[key[0]][key[1]]=true;$(key[1]+key[0]).classList.add('held');});
window.addEventListener('keyup',e=>{const key=keys[e.key.toLowerCase()];if(!key)return;inputs[key[0]][key[1]]=false;$(key[1]+key[0]).classList.remove('held');});
window.addEventListener('blur',()=>{clearInput();if(state==='running')pause();});
window.addEventListener('pagehide',()=>{clearInput();if(state==='running')pause();});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='running')pause();});
window.addEventListener('resize',()=>{if(state==='running')pause();resize();});
bindMenu();resize();requestAnimationFrame(frame);
