import { authenticate, pathRef, update, runTransaction, push, set, onValue } from "./firebase-service.js";
import { Room } from "./room.js"; import { GPS } from "./gps.js"; import { GameMap } from "./map.js"; import { SAFETY_ITEMS,isNameValid } from "./safety.js"; import { makeWitness } from "./witness.js"; import { captureState } from "./capture.js"; import { formatClock,normalizeRoomId } from "./utils.js";
const $=s=>document.querySelector(s), screens=[...document.querySelectorAll(".screen")]; let mode="create",uid,room,data,myPos,map,gps,sendTimer,tickTimer,captureSince=0,lastWitnessPos=null,roleSeen=false;
const show=id=>{screens.forEach(x=>x.classList.toggle("active",x.id===id));if(id==="game"){map??=new GameMap("map");map.show();}}; const toast=m=>{const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2300)};
document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>{const to=b.dataset.go;if(to==="create"||to==="join"){mode=to;$("#entryTitle").textContent=to==="create"?"部屋を作る":"部屋に参加";$("#roomField").hidden=to!=="join";show("profile")}else show(to)});
$("#safetyItems").innerHTML=SAFETY_ITEMS.map(x=>`<p>✓ ${x}</p>`).join(""); $("#agree").onchange=e=>$("#gpsStart").disabled=!e.target.checked; $("#roomId").oninput=e=>e.target.value=normalizeRoomId(e.target.value);
$("[data-modal=how]").onclick=()=>$("#how").showModal();$(".dialog-close").onclick=()=>$("#how").close();
$("#toSafety").onclick=()=>{if(!isNameValid($("#name").value))return toast("表示名を1〜12文字で入力してください");if(mode==="join"&&$("#roomId").value.length!==6)return toast("6桁の部屋IDを入力してください");show("safety")};
const gpsStatus=(m,state)=>{$("#gpsStatus").textContent=m;if(room?.id)room.patch(`players/${uid}`,{gpsStatus:m}).catch(()=>{})};
$("#gpsStart").onclick=async()=>{try{uid=(await authenticate()).uid;gps??=new GPS((p,s)=>{myPos=p;map?.position(p);$("#warning").hidden=!s.warning;$("#warning").textContent=s.stopped?"安全停止：乗り物から降り、安全な場所で停止してください":"速度が高いようです。周囲を確認してください"},gpsStatus);gps.start();room=new Room(uid,renderRoom);if(mode==="create")await room.create($("#name").value.trim());else await room.join($("#roomId").value,$("#name").value.trim());show("lobby")}catch(e){toast(e.message)}};
function renderRoom(next){if(!next){toast("部屋が終了しました");show("home");return}data=next;const me=data.players?.[uid];if(!me)return;$("#roomCode").textContent=room.id;const list=Object.entries(data.players||{});$("#count").textContent=`${list.length} / 6`;$("#players").innerHTML=list.map(([id,p])=>`<div class="player"><b>${escapeHtml(p.displayName)}${id===data.meta.hostUid?" ★":""}</b><small>${p.role?roleLabel(p.role):"役割未定"}・${p.isReady?"準備OK":"準備中"}・${p.isOnline===false?"切断":"接続中"}</small></div>`).join("");const host=data.meta.hostUid===uid;$("#settings").style.opacity=host?1:.65;$("#settings").querySelectorAll("select").forEach(x=>x.disabled=!host);$("#start").hidden=!host;$("#start").disabled=list.length<2||!list.every(([,p])=>p.isReady);$("#ready").textContent=me.isReady?"準備を取り消す":"準備完了";
 if(data.game?.phase==="headstart"||data.game?.phase==="playing"){if(!roleSeen){roleSeen=true;$("#roleName").textContent=roleLabel(me.role);$("#roleName").style.color=me.role==="criminal"?"var(--red)":"var(--blue)";$("#roleHelp").textContent=me.role==="criminal"?"制限時間まで逃げ切ってください。刑事の位置は表示されません。":"目撃情報を手掛かりに犯人を追跡してください。";show("role")}}
 if(data.game?.phase==="finished"){clearInterval(sendTimer);gps?.stop();$("#winner").textContent=data.game.winnerRole==="criminal"?"犯人の勝利":"刑事の勝利";const capturer=data.players?.[data.game.capturedByUid]?.displayName;$("#resultText").textContent=capturer?`${capturer} が犯人を捕獲しました。`:"犯人が制限時間まで逃げ切りました。";show("result")}}
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const roleLabel=r=>r==="criminal"?"犯人":"刑事";
$("#copyRoom").onclick=()=>navigator.clipboard.writeText(room.id).then(()=>toast("部屋IDをコピーしました"));$("#ready").onclick=()=>room.ready(!data.players[uid].isReady);$("#leave").onclick=leave;$("#resultLeave").onclick=leave;async function leave(){gps?.stop();clearInterval(sendTimer);clearInterval(tickTimer);await room?.leave();show("home")}
document.querySelectorAll("#settings select").forEach(x=>x.onchange=()=>room.patch("settings",{durationSeconds:+$("#duration").value,witnessIntervalSeconds:+$("#witness").value,captureDistanceMeters:+$("#distance").value,headStartSeconds:+$("#headstart").value,roleAssignmentMode:$("#roles").value}));
$("#start").onclick=async()=>{const ids=Object.keys(data.players),criminal=data.settings.roleAssignmentMode==="manual"?uid:ids[Math.floor(Math.random()*ids.length)],now=Date.now(),updates={};ids.forEach(id=>updates[`players/${id}/role`]=id===criminal?"criminal":"detective");updates["meta/status"]="playing";updates["game"]={phase:"headstart",startedAt:now,headStartEndsAt:now+data.settings.headStartSeconds*1000,endsAt:now+(data.settings.headStartSeconds+data.settings.durationSeconds)*1000,generationId:0};await update(pathRef(room.id),updates)};
$("#roleOk").onclick=enterGame;function enterGame(){show("game");const me=data.players[uid];$("#roleBadge").textContent=roleLabel(me.role);$("#roleBadge").style.color=me.role==="criminal"?"var(--red)":"var(--blue)";map.position(myPos);clearInterval(sendTimer);sendTimer=setInterval(()=>{if(myPos)room.patch(`players/${uid}/position`,myPos)},(data.settings.positionSendIntervalSeconds||5)*1000);tick() ;clearInterval(tickTimer);tickTimer=setInterval(tick,1000);onValue(pathRef(`${room.id}/witnessReports`),s=>{const reports=Object.values(s.val()||{}).sort((a,b)=>b.createdAt-a.createdAt);if(me.role==="detective"&&reports[0]){$("#witnessText").textContent=reports[0].message;$("#witnessCard").hidden=false;map.witness(reports[0])}})}
async function tick(){if(!data?.game)return;const now=Date.now(),me=data.players[uid],head=Math.max(0,Math.ceil((data.game.headStartEndsAt-now)/1000)),remaining=Math.max(0,Math.ceil((data.game.endsAt-now)/1000));$("#timer").textContent=head?`先行 ${head}`:formatClock(remaining);const interval=data.settings.witnessIntervalSeconds,elapsed=Math.max(0,Math.floor((now-data.game.headStartEndsAt)/1000));$("#nextWitness").textContent=head?"待機中":`${interval-(elapsed%interval)}秒`;
 if(data.game.phase==="headstart"&&now>=data.game.headStartEndsAt&&data.meta.hostUid===uid)await room.patch("game",{phase:"playing"});if(remaining<=0&&data.game.phase!=="finished"&&data.meta.hostUid===uid)await finish("criminal");
 if(data.game.phase==="playing"&&data.meta.hostUid===uid&&elapsed>0&&elapsed%interval===0&&data.game.generationId!==Math.floor(elapsed/interval)){const criminal=Object.values(data.players).find(p=>p.role==="criminal");if(criminal?.position){const report=makeWitness(now,criminal.position,lastWitnessPos,Math.min(3,1+Math.floor(elapsed/(interval*3))));lastWitnessPos=criminal.position;await push(pathRef(`${room.id}/witnessReports`),report);await room.patch("game",{generationId:Math.floor(elapsed/interval)})}}
 if(me.role==="detective"&&data.game.phase==="playing"){const criminal=Object.values(data.players).find(p=>p.role==="criminal"),state=captureState(myPos,criminal?.position,data.settings,captureSince,now);if(state.valid&&!captureSince)captureSince=now;if(!state.valid)captureSince=0;$("#capture").hidden=!state.valid;$("#capture").textContent=`接近中 ${Math.floor(state.progress*data.settings.captureHoldSeconds)} / ${data.settings.captureHoldSeconds}秒`;if(state.progress>=1)await runTransaction(pathRef(`${room.id}/game`),g=>g?.phase==="playing"?{...g,phase:"finished",winnerRole:"detective",capturedByUid:uid,capturedAt:Date.now()}:undefined)}}
async function finish(winner){await runTransaction(pathRef(`${room.id}/game`),g=>g?.phase!=="finished"?{...g,phase:"finished",winnerRole:winner,finishedAt:Date.now()}:undefined)}
$("#locate").onclick=()=>map.center(myPos);$("#fold").onclick=()=>$("#details").hidden=!$("#details").hidden;$("#rematch").onclick=async()=>{roleSeen=false;await room.patch("game",{phase:"lobby",winnerRole:null,capturedByUid:null});await room.patch("meta",{status:"lobby"});for(const id of Object.keys(data.players))await room.patch(`players/${id}`,{isReady:false,role:"",position:null});show("lobby")};
document.addEventListener("visibilitychange",()=>{if(!document.hidden){gpsStatus("再確認中");toast("復帰しました。GPSと通信を再確認します")}});window.addEventListener("pagehide",()=>gps?.stop());show("home");
