(function () {
  "use strict";
  class RaceGame {
    constructor(canvas,sound,settings,onEnd,options={}) {
      this.canvas=canvas; this.ctx=canvas.getContext("2d"); this.sound=sound; this.settings=settings; this.onEnd=onEnd; this.controlsRoot=options.controlsRoot;
      this.running=false; this.finished=false; this.paused=false; this.last=0; this.fps=60; this.elapsed=0; this.time=90; this.distance=0; this.course=5200; this.speed=40; this.maxSpeed=0; this.speedTotal=0; this.score=0; this.lane=0; this.input={left:false,right:false,accel:false,brake:false}; this.pressed={boost:false}; this.autoAccel=true; this.boost=0; this.invincible=0; this.shake=0; this.curve=0; this.drift=false; this.warningCd=0; this.overtakeCd=0; this.accelBand=0; this.stats={overtakes:0,crashes:0,boosts:0,items:0}; this.cleanup=[]; this.traffic=[]; this.items=[]; this.spawnClock=0; this.boundLoop=t=>this.loop(t);
    }
    start(){ this.resize(); this.bind(); this.sound.resetPlayStats(); this.sound.play("raceStart"); this.sound.startLoop("raceEngine",{gain:.55,playbackRate:.85}); this.running=true; this.last=performance.now(); requestAnimationFrame(this.boundLoop); }
    stop(){ this.running=false; this.sound.stopLoop("raceEngine"); this.cleanup.splice(0).forEach(fn=>fn()); }
    resize(){ const r=this.canvas.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1); this.canvas.width=Math.round(r.width*d); this.canvas.height=Math.round(r.height*d); this.ctx.setTransform(d,0,0,d,0,0); this.w=r.width; this.h=r.height; }
    bind(){ const set=(n,v)=>{ if(n==="boost"&&v&&!this.input[n])this.pressed.boost=true; if((n==="brake"||n==="accel")&&v&&!this.input[n])this.sound.play(n==="brake"?"raceBrake":"raceAccelerate"); this.input[n]=v; };
      this.controlsRoot?.querySelectorAll("[data-race-control]").forEach(b=>{const n=b.dataset.raceControl,d=e=>{e.preventDefault();set(n,true);b.classList.add("is-pressed")},u=e=>{e.preventDefault();set(n,false);b.classList.remove("is-pressed")}; b.addEventListener("pointerdown",d); ["pointerup","pointercancel","lostpointercapture"].forEach(x=>b.addEventListener(x,u)); this.cleanup.push(()=>{b.removeEventListener("pointerdown",d);["pointerup","pointercancel","lostpointercapture"].forEach(x=>b.removeEventListener(x,u));});});
      const map={ArrowLeft:"left",ArrowRight:"right",ArrowUp:"accel",ArrowDown:"brake",Space:"boost"},kd=e=>{if(map[e.code]){e.preventDefault();set(map[e.code],true)}},ku=e=>{if(map[e.code]){e.preventDefault();set(map[e.code],false)}}; window.addEventListener("keydown",kd);window.addEventListener("keyup",ku);this.cleanup.push(()=>{window.removeEventListener("keydown",kd);window.removeEventListener("keyup",ku)});
    }
    spawn(){ const lane=[-1,0,1][Math.floor(Math.random()*3)]; this.traffic.push({lane,z:1.05,speed:55+Math.random()*85,wobble:Math.random()>.65,passed:false,color:["#ff3b68","#ffe45d","#48e9e1"][Math.floor(Math.random()*3)]}); if(Math.random()<.22)this.items.push({lane:[-1,0,1][Math.floor(Math.random()*3)],z:1.2}); }
    update(dt){ this.elapsed+=dt; this.time=Math.max(0,this.time-dt); this.invincible=Math.max(0,this.invincible-dt);this.shake=Math.max(0,this.shake-dt);this.warningCd-=dt;this.overtakeCd-=dt;this.boost=Math.max(0,this.boost-dt); this.curve=Math.sin(this.distance/620)*.7;
      const steer=Number(this.input.right)-Number(this.input.left); this.lane=Math.max(-1.25,Math.min(1.25,this.lane+steer*dt*1.8)); const accelerating=this.autoAccel||this.input.accel; this.speed+=((accelerating?175:80)-this.speed)*dt*.75; if(this.input.brake)this.speed-=150*dt; if(this.boost>0)this.speed+=95*dt; this.speed=Math.max(25,Math.min(this.boost>0?230:200,this.speed));
      if(this.pressed.boost){this.pressed.boost=false;if(this.stats.items>0){this.stats.items--;this.boost=3;this.stats.boosts++;this.sound.play("raceBoost");}}
      const drifting=Math.abs(steer)>.5&&this.speed>145&&Math.abs(this.curve)>.35;if(drifting&&!this.drift)this.sound.play("raceDrift");this.drift=drifting;
      const band=this.speed>155?2:this.speed>95?1:0;if(band>this.accelBand)this.sound.play("raceAccelerate");this.accelBand=band;
      this.sound.setLoopPlaybackRate("raceEngine",this.boost>0?1.3:.85+(this.speed/200)*.3);this.sound.setLoopVolume("raceEngine",this.paused?0:.55);
      const travel=this.speed*dt*.42;this.distance+=travel;this.speedTotal+=this.speed*dt;this.maxSpeed=Math.max(this.maxSpeed,this.speed);this.score+=Math.round(travel*(1+this.speed/180));this.spawnClock-=dt;if(this.spawnClock<=0){this.spawn();this.spawnClock=.9+Math.random()*1.2;}
      this.traffic.forEach(car=>{car.z-=dt*(.13+Math.max(0,this.speed-car.speed)/500);if(car.wobble)car.lane+=Math.sin(this.elapsed*2+car.speed)*dt*.12;if(car.z<.25&&!car.passed&&Math.abs(car.lane-this.lane)>.48){car.passed=true;this.stats.overtakes++;this.score+=250;if(this.overtakeCd<=0){this.sound.play("raceOvertake");this.overtakeCd=.6}}if(car.z<.43&&car.z>.18&&Math.abs(car.lane-this.lane)<.38&&this.invincible<=0){this.invincible=1.3;this.shake=.35;this.speed*=.42;this.stats.crashes++;this.sound.play("raceCrash");}});this.traffic=this.traffic.filter(c=>c.z>0);
      this.items.forEach(item=>{item.z-=dt*.18;if(item.z<.38&&item.z>.18&&Math.abs(item.lane-this.lane)<.38){item.z=-1;this.stats.items++;this.sound.play("raceItem");}});this.items=this.items.filter(i=>i.z>0);
      const danger=this.traffic.some(c=>c.z<.62&&c.z>.35&&Math.abs(c.lane-this.lane)<.34);if(danger&&this.speed>135&&this.warningCd<=0){this.sound.play("raceWarning");this.warningCd=2.5;}
      if(this.distance>=this.course)this.finish(true);else if(this.time<=0)this.finish(false);
    }
    project(lane,z){const horizon=this.h*.25,p=Math.max(0,Math.min(1,1-z)),roadNear=this.w*.9,roadFar=this.w*.12,road=roadFar+(roadNear-roadFar)*p;return{x:this.w/2+lane*road*.27+this.curve*(1-p)*this.w*.08,y:horizon+p*(this.h-horizon),scale:.18+p*.95,road};}
    draw(){const c=this.ctx,w=this.w,h=this.h;c.save();if(this.shake>0)c.translate((Math.random()-.5)*10,(Math.random()-.5)*7);const sky=c.createLinearGradient(0,0,0,h);sky.addColorStop(0,"#14264d");sky.addColorStop(.45,"#6ac5ca");sky.addColorStop(.46,"#357a39");sky.addColorStop(1,"#17391e");c.fillStyle=sky;c.fillRect(0,0,w,h);c.fillStyle="#26303b";c.beginPath();c.moveTo(w*.44,h*.25);c.lineTo(w*.56,h*.25);c.lineTo(w*.95,h);c.lineTo(w*.05,h);c.fill();c.strokeStyle="#f5f7ff";c.lineWidth=3;for(let i=0;i<9;i++){const z=((i/9+this.distance/170)%1);const a=this.project(-.5,z),b=this.project(-.5,Math.max(0,z-.055));c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();const d=this.project(.5,z),e=this.project(.5,Math.max(0,z-.055));c.beginPath();c.moveTo(d.x,d.y);c.lineTo(e.x,e.y);c.stroke();}
      [...this.traffic].sort((a,b)=>b.z-a.z).forEach(car=>{const p=this.project(car.lane,car.z),cw=34*p.scale,ch=54*p.scale;c.fillStyle=car.color;c.fillRect(p.x-cw/2,p.y-ch,cw,ch);c.fillStyle="#111";c.fillRect(p.x-cw*.28,p.y-ch*.83,cw*.56,ch*.28);});this.items.forEach(item=>{const p=this.project(item.lane,item.z);c.fillStyle="#ffe45d";c.beginPath();c.arc(p.x,p.y-20*p.scale,12*p.scale,0,Math.PI*2);c.fill();c.fillStyle="#111";c.fillText("B",p.x-4*p.scale,p.y-16*p.scale);});const px=w/2+this.lane*w*.26,py=h*.86;c.globalAlpha=this.invincible>0&&Math.floor(this.elapsed*12)%2?.35:1;c.fillStyle=this.boost>0?"#ffe45d":"#ff3b68";c.beginPath();c.moveTo(px,py-58);c.lineTo(px-28,py+18);c.lineTo(px+28,py+18);c.closePath();c.fill();c.globalAlpha=1;if(this.boost>0){c.strokeStyle="#48e9e1";for(let i=0;i<8;i++){c.beginPath();c.moveTo(Math.random()*w,py);c.lineTo(Math.random()*w,h);c.stroke();}}c.restore();}
    loop(t){if(!this.running)return;const dt=Math.min(.05,(t-this.last)/1000);this.last=t;this.fps+=(1/Math.max(.001,dt)-this.fps)*.08;if(!this.paused)this.update(dt);this.draw();requestAnimationFrame(this.boundLoop);}
    finish(clear){if(this.finished)return;this.finished=true;this.running=false;this.sound.stopLoop("raceEngine");this.sound.play(clear?"raceGoal":"raceGameOver");this.onEnd({mode:"race",clear,score:this.score,counts:this.sound.getPlayStats(),loopStats:this.sound.getLoopStats(),stats:{time:this.elapsed,maxSpeed:this.maxSpeed,averageSpeed:this.elapsed?this.speedTotal/this.elapsed:0,...this.stats}});}
    getHudState(){return{mode:"race",score:this.score,time:this.time,best:0,speed:this.speed,distance:this.distance/this.course};}
    getDebugState(){return{game:"race",playerState:this.paused?"PAUSED":this.drift?"DRIFT":"RACING",fps:Math.round(this.fps),speed:Math.round(this.speed),distance:`${Math.round(this.distance/this.course*100)}%`,enemies:this.traffic.length,crash:this.invincible.toFixed(1),boost:this.boost.toFixed(1),engineRate:(.85+(this.speed/200)*.3).toFixed(2),engineLoop:this.sound.isLoopPlaying("raceEngine")};}
  }
  window.RaceGame=RaceGame;
})();
