(function () {
  "use strict";
  class RhythmGame {
    constructor(canvas,sound,settings,onEnd,options={}){this.canvas=canvas;this.sound=sound;this.settings=settings;this.onEnd=onEnd;this.controlsRoot=options.controlsRoot;this.stageId=options.rhythmStage||"eight";this.chart=window.RhythmChart.create(this.stageId);this.renderer=new window.RhythmRenderer(canvas);this.notes=this.chart.notes.map(n=>({...n}));this.running=false;this.finished=false;this.needsRestart=false;this.startAudioTime=0;this.startPerfTime=0;this.score=0;this.combo=0;this.maxCombo=0;this.fever=false;this.judgeText="";this.judgeTimer=0;this.padFlash=[0,0,0,0];this.fps=60;this.lastFrame=0;this.missSoundAt=-9;this.comboVoices=new Set();this.offsets=[];this.judgementLog=[];this.cleanup=[];this.stats={perfect:0,great:0,good:0,miss:0};this.laneSounds=["rhythmKick","rhythmSnare","rhythmHiHat","rhythmClap"];this.boundLoop=(time)=>this.loop(time);}
    clock(){return this.sound.context?.state==="running"?this.sound.context.currentTime:performance.now()/1000;}
    position(){return this.clock()-this.startAudioTime+(Number(this.settings.rhythmOffset)||0)/1000;}
    start(){this.sound.resetPlayStats();this.resize();this.bind();this.resetRun();this.sound.play("rhythmStart");requestAnimationFrame(this.boundLoop);}
    resetRun(){this.notes=this.chart.notes.map(n=>({...n}));this.running=true;this.finished=false;this.needsRestart=false;this.startAudioTime=this.clock()+3;this.startPerfTime=performance.now()/1000+3;this.score=0;this.combo=0;this.maxCombo=0;this.fever=false;this.stats={perfect:0,great:0,good:0,miss:0};this.offsets=[];this.judgementLog=[];this.comboVoices.clear();}
    stop(){this.running=false;this.cleanup.splice(0).forEach(fn=>fn());}
    resize(){this.renderer.resize();}
    bind(){const down=(event)=>{event.preventDefault();const button=event.currentTarget,lane=Number(button.dataset.rhythmLane);button.classList.add("is-pressed");this.input(lane);},up=(event)=>event.currentTarget.classList.remove("is-pressed");this.controlsRoot?.querySelectorAll("[data-rhythm-lane]").forEach(button=>{button.addEventListener("pointerdown",down);button.addEventListener("pointerup",up);button.addEventListener("pointercancel",up);this.cleanup.push(()=>{button.removeEventListener("pointerdown",down);button.removeEventListener("pointerup",up);button.removeEventListener("pointercancel",up);});});
      const keys={KeyD:0,KeyF:1,KeyJ:2,KeyK:3},keydown=(event)=>{if(event.repeat||keys[event.code]==null)return;event.preventDefault();this.input(keys[event.code]);};window.addEventListener("keydown",keydown);this.cleanup.push(()=>window.removeEventListener("keydown",keydown));
      const visibility=()=>{if(document.hidden&&this.running){this.needsRestart=true;}};document.addEventListener("visibilitychange",visibility);this.cleanup.push(()=>document.removeEventListener("visibilitychange",visibility));}
    input(lane){if(!this.running)return;if(this.needsRestart){this.resetRun();return;}this.sound.play(this.laneSounds[lane]);this.padFlash[lane]=.12;const now=this.position();let candidate=null,best=Infinity;for(const note of this.notes){if(note.status!=="pending"||note.lane!==lane)continue;const distance=Math.abs(now-note.time);if(distance<best){best=distance;candidate=note;}if(note.time>now+.18)break;}if(!candidate||best>window.RhythmJudge.windows.good)return;const delta=now-candidate.time,judge=window.RhythmJudge.judge(delta);candidate.status="hit";candidate.judge=judge;this.applyJudge(judge,delta,lane,candidate.time);}
    applyJudge(judge,delta,lane,target){const key=judge.toLowerCase();this.stats[key]+=1;this.combo+=1;this.maxCombo=Math.max(this.maxCombo,this.combo);this.fever=this.combo>=30;const multiplier=(1+Math.min(1.5,this.combo/100))*(this.fever?2:1);this.score+=Math.round(window.RhythmJudge.score(judge)*multiplier);this.judgeText=judge;this.judgeTimer=.35;this.offsets.push(delta);if(this.offsets.length>100)this.offsets.shift();this.log(lane,target,target+delta,delta,judge);if(this.settings.rhythmJudgeVoice==="always")this.sound.play(`rhythm${judge[0]}${judge.slice(1).toLowerCase()}`);for(const milestone of [10,30,50])if(this.combo>=milestone&&!this.comboVoices.has(milestone)){this.comboVoices.add(milestone);this.sound.play(`rhythmCombo${milestone}`);if(milestone===30)this.sound.play("rhythmFever");}}
    miss(note){note.status="miss";this.stats.miss+=1;this.combo=0;this.fever=false;this.judgeText="MISS";this.judgeTimer=.35;this.log(note.lane,note.time,this.position(),this.position()-note.time,"MISS");if(this.settings.rhythmJudgeVoice!=="off"&&this.position()-this.missSoundAt>.28){this.missSoundAt=this.position();this.sound.play("rhythmMiss");}}
    log(lane,target,input,delta,judge){this.judgementLog.push({lane,target,input,offsetMs:Math.round(delta*1000),judge});if(this.judgementLog.length>50)this.judgementLog.shift();}
    loop(time){if(!this.running)return;const dt=Math.min(.05,(time-(this.lastFrame||time))/1000);this.lastFrame=time;this.fps+=(1/Math.max(.001,dt)-this.fps)*.08;if(!this.needsRestart){const position=this.position();for(const note of this.notes)if(note.status==="pending"&&position-note.time>window.RhythmJudge.windows.good)this.miss(note);if(position>this.chart.duration)this.finish();}this.judgeTimer=Math.max(0,this.judgeTimer-dt);if(!this.judgeTimer)this.judgeText="";this.padFlash=this.padFlash.map(value=>Math.max(0,value-dt));this.renderer.draw(this);if(this.running)requestAnimationFrame(this.boundLoop);}
    finish(){if(this.finished)return;this.finished=true;this.running=false;const fullCombo=this.stats.miss===0,allPerfect=fullCombo&&this.stats.great===0&&this.stats.good===0;this.sound.play("rhythmFinish");this.onEnd({mode:"rhythm",clear:true,score:this.score,counts:this.sound.getPlayStats(),stats:{...this.stats,maxCombo:this.maxCombo,accuracy:window.RhythmJudge.accuracy(this.stats),fullCombo,allPerfect,stageId:this.chart.id,stageName:this.chart.name,bpm:this.chart.bpm,averageOffsetMs:this.offsets.length?Math.round(this.offsets.reduce((a,b)=>a+b,0)/this.offsets.length*1000):0}});}
    getHudState(){return{mode:"rhythm",score:this.score,best:this.score,combo:this.combo,time:Math.max(0,this.chart.duration-this.position())};}
    getDebugState(){const pending=this.notes.filter(note=>note.status==="pending").length;return{game:"rhythm",fps:Math.round(this.fps),playerState:this.needsRestart?"RESTART WAIT":"PLAYING",bpm:this.chart.bpm,position:this.position().toFixed(3),audioTime:this.sound.context?.currentTime?.toFixed(3)||"--",startAudioTime:this.startAudioTime.toFixed(3),notes:this.notes.length,pending,offset:this.settings.rhythmOffset||0,averageOffset:this.offsets.length?Math.round(this.offsets.reduce((a,b)=>a+b,0)/this.offsets.length*1000):0,lastJudge:this.judgementLog.length?this.judgementLog[this.judgementLog.length-1]:null};}
  }
  window.RhythmGame=RhythmGame;
})();
