(function(){"use strict";
const canvas=document.querySelector("#gameCanvas"),ctx=canvas.getContext("2d"),distanceEl=document.querySelector("#distance"),debugButton=document.querySelector("#debugButton"),retryButton=document.querySelector("#retryButton"),panel=document.querySelector("#debugPanel"),paramRoot=document.querySelector("#parameters"),fpsEl=document.querySelector("#fps"),physics=new QWOPPhysics.RunnerPhysics(),pointers=new Map();let debug=false,cameraX=0,last=performance.now(),fps=60;
const specs={gravity:["重力",.45,1.7,.01],groundFriction:["地面摩擦",.2,1.5,.01],footFriction:["足の摩擦",.2,1.8,.01],hipTorque:["股関節トルク",.001,.012,.0001],kneeTorque:["ひざトルク",.001,.012,.0001],jointDamping:["関節減衰",.05,1.2,.01],postureTorque:["姿勢維持トルク",0,.004,.00005]};
function resize(){let r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);ctx.setTransform(d,0,0,d,0,0)}
function setKey(k,on){physics.setKey(k,on);document.querySelectorAll(`[data-key="${k}"]`).forEach(e=>e.classList.toggle("active",on))}
document.addEventListener("keydown",e=>{let k=e.key.toLowerCase();if(k in physics.keys){e.preventDefault();setKey(k,true)}});document.addEventListener("keyup",e=>{let k=e.key.toLowerCase();if(k in physics.keys){e.preventDefault();setKey(k,false)}});window.addEventListener("blur",()=>Object.keys(physics.keys).forEach(k=>setKey(k,false)));
document.querySelectorAll("[data-key]").forEach(btn=>{btn.addEventListener("pointerdown",e=>{e.preventDefault();btn.setPointerCapture(e.pointerId);pointers.set(e.pointerId,btn.dataset.key);setKey(btn.dataset.key,true)});let up=e=>{let k=pointers.get(e.pointerId);if(!k)return;pointers.delete(e.pointerId);if(![...pointers.values()].includes(k))setKey(k,false)};btn.addEventListener("pointerup",up);btn.addEventListener("pointercancel",up);btn.addEventListener("lostpointercapture",up);btn.addEventListener("contextmenu",e=>e.preventDefault())});
retryButton.onclick=()=>{Object.keys(physics.keys).forEach(k=>setKey(k,false));pointers.clear();physics.reset();cameraX=0};
Object.entries(specs).forEach(([name,s])=>{let row=document.createElement("div");row.className="parameter";row.innerHTML=`<label>${s[0]}</label><output></output><input type="range" min="${s[1]}" max="${s[2]}" step="${s[3]}">`;let input=row.querySelector("input"),out=row.querySelector("output");input.value=physics.params[name];input.oninput=()=>{physics.setParameter(name,input.value);out.value=Number(input.value).toFixed(name.includes("Torque")?5:2)};input.oninput();paramRoot.append(row)});
debugButton.onclick=()=>{debug=!debug;panel.hidden=!debug;debugButton.textContent=debug?"DEBUG ON":"DEBUG"};document.querySelector("#resetParameters").onclick=()=>{physics.resetParameters();Object.keys(specs).forEach(n=>{let i=[...paramRoot.querySelectorAll("input")][Object.keys(specs).indexOf(n)];i.value=physics.params[n];i.oninput()})};
function path(body){ctx.beginPath();body.vertices.forEach((v,i)=>i?ctx.lineTo(v.x,v.y):ctx.moveTo(v.x,v.y));ctx.closePath()}
function body(b,color){path(b);ctx.fillStyle=color;ctx.fill();ctx.lineWidth=3;ctx.strokeStyle="#07111f";ctx.stroke()}
function draw(w,h){ctx.clearRect(0,0,w,h);let sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,"#c9f0f2");sky.addColorStop(1,"#87ccd7");ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(-cameraX,h-473);let left=cameraX-200,right=cameraX+w+200;ctx.fillStyle="#d9bc79";ctx.fillRect(left,473,right-left,120);ctx.fillStyle="#263849";ctx.fillRect(left,473,right-left,8);ctx.strokeStyle="#26384938";for(let x=Math.floor(left/72)*72;x<right;x+=72){ctx.beginPath();ctx.moveTo(x,481);ctx.lineTo(x-34,522);ctx.stroke()}ctx.fillStyle="#163044";ctx.font="800 11px monospace";ctx.fillText("START",physics.startX-24,462);ctx.fillRect(physics.startX,443,3,30);for(let m=-5;m<150;m+=5){let x=physics.startX+m*72;ctx.fillRect(x,465,2,8);if(m%10===0)ctx.fillText(`${m}m`,x-10,454)}let b=physics.bodies;body(b.leftThigh,"#ef5f63");body(b.leftShin,"#f18b62");body(b.leftFoot,"#f5f0df");body(b.rightThigh,"#31b9c5");body(b.rightShin,"#55d5d0");body(b.rightFoot,"#f5f0df");body(b.torso,"#f7cf59");ctx.beginPath();ctx.arc(b.head.position.x,b.head.position.y,b.head.circleRadius,0,Math.PI*2);ctx.fillStyle="#f3b58d";ctx.fill();ctx.lineWidth=3;ctx.strokeStyle="#07111f";ctx.stroke();ctx.fillStyle="#07111f";ctx.beginPath();ctx.arc(b.head.position.x+8,b.head.position.y-5,2.3,0,Math.PI*2);ctx.fill();if(debug)drawDebug();ctx.restore()}
function drawDebug(){let b=physics.bodies;ctx.strokeStyle="#ff2a63";ctx.lineWidth=1;Object.values(b).forEach(x=>{path(x);ctx.stroke()});ctx.fillStyle="#ff2a63";physics.constraints.forEach(c=>{let x=(c.bodyA.position.x+c.bodyB.position.x)/2,y=(c.bodyA.position.y+c.bodyB.position.y)/2;ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill()});ctx.fillStyle="#07111f";ctx.font="700 11px monospace";ctx.fillText(`v ${b.torso.velocity.x.toFixed(2)}, ${b.torso.velocity.y.toFixed(2)} body ${b.torso.angle.toFixed(2)}`,cameraX+16,24);ctx.fillText(`hip L ${(b.leftThigh.angle-b.torso.angle).toFixed(2)} R ${(b.rightThigh.angle-b.torso.angle).toFixed(2)} knee L ${(b.leftShin.angle-b.leftThigh.angle).toFixed(2)} R ${(b.rightShin.angle-b.rightThigh.angle).toFixed(2)}`,cameraX+16,41);ctx.beginPath();ctx.arc(b.torso.position.x,b.torso.position.y,5,0,Math.PI*2);ctx.fillStyle="#ffe066";ctx.fill()}
function frame(now){let dt=Math.min(now-last,34);last=now;physics.step(dt);let w=canvas.clientWidth,h=canvas.clientHeight,target=physics.bodies.torso.position.x-w*.38;cameraX+=(target-cameraX)*(1-Math.pow(.005,dt/1000));draw(w,h);distanceEl.textContent=physics.distance.toFixed(2)+" m";fps+=(1000/Math.max(dt,1)-fps)*.08;fpsEl.textContent=Math.round(fps)+" FPS";requestAnimationFrame(frame)}
window.addEventListener("resize",resize,{passive:true});document.addEventListener("visibilitychange",()=>last=performance.now());resize();requestAnimationFrame(frame)})();
