(function(){"use strict";
const{Engine,Bodies,Composite,Constraint,Events}=Matter;
const DEFAULTS={gravity:.45,groundFriction:.92,footFriction:1.15,hipTorque:.0052,kneeTorque:.0044,jointDamping:.42,postureTorque:.00115},GROUP=-17;
function box(x,y,w,h,o={}){return Bodies.rectangle(x,y,w,h,{density:.0022,friction:.7,frictionStatic:1.1,restitution:.02,chamfer:{radius:Math.min(w,h)*.22},collisionFilter:{group:GROUP},...o})}
function joint(a,pa,b,pb){return Constraint.create({bodyA:a,pointA:pa,bodyB:b,pointB:pb,length:2,stiffness:.94,damping:.28})}
class RunnerPhysics{
 constructor(){this.params={...DEFAULTS};this.engine=Engine.create({positionIterations:10,velocityIterations:8,constraintIterations:4});this.engine.gravity.scale=.00115;this.keys={q:false,w:false,o:false,p:false};this.reset();Events.on(this.engine,"beforeUpdate",()=>this.beforeUpdate())}
 reset(){Composite.clear(this.engine.world,false,true);Engine.clear(this.engine);this.engine.gravity.y=this.params.gravity;this.startX=260;this.ground=Bodies.rectangle(10000,500,20500,54,{isStatic:true,friction:this.params.groundFriction,frictionStatic:1.5,label:"ground"});Composite.add(this.engine.world,this.ground);this.createRunner()}
 createRunner(){const x=this.startX,t=box(x,292,42,112,{label:"torso",density:.0033,angle:-.035}),h=Bodies.circle(x+2,214,25,{label:"head",density:.0018,collisionFilter:{group:GROUP}}),lt=box(x-15,376,25,82,{label:"left thigh",angle:.13}),rt=box(x+17,374,25,82,{label:"right thigh",angle:-.2}),ls=box(x-24,443,21,77,{label:"left shin",angle:.12}),rs=box(x+31,439,21,77,{label:"right shin",angle:-.15}),lf=box(x-8,481,51,17,{label:"left foot",friction:this.params.footFriction}),rf=box(x+47,479,51,17,{label:"right foot",friction:this.params.footFriction});this.bodies={torso:t,head:h,leftThigh:lt,rightThigh:rt,leftShin:ls,rightShin:rs,leftFoot:lf,rightFoot:rf};this.constraints=[joint(t,{x:0,y:-55},h,{x:0,y:24}),joint(t,{x:-13,y:49},lt,{x:0,y:-39}),joint(t,{x:13,y:49},rt,{x:0,y:-39}),joint(lt,{x:0,y:39},ls,{x:0,y:-36}),joint(rt,{x:0,y:39},rs,{x:0,y:-36}),joint(ls,{x:0,y:36},lf,{x:-15,y:0}),joint(rs,{x:0,y:36},rf,{x:-15,y:0})];this.limits=[[t,lt,-1.1,1.05],[t,rt,-1.1,1.05],[lt,ls,-1.55,.3],[rt,rs,-1.55,.3],[ls,lf,-.65,.65],[rs,rf,-.65,.65]];Composite.add(this.engine.world,[...Object.values(this.bodies),...this.constraints])}
 setKey(k,v){if(k in this.keys)this.keys[k]=v}
 setParameter(n,v){if(!(n in this.params))return;this.params[n]=Number(v);this.engine.gravity.y=this.params.gravity;this.ground.friction=this.params.groundFriction;this.bodies.leftFoot.friction=this.bodies.rightFoot.friction=this.params.footFriction}
 resetParameters(){Object.assign(this.params,DEFAULTS);Object.keys(this.params).forEach(k=>this.setParameter(k,this.params[k]))}
 drive(a,b,target,power){let e=Math.max(-1.25,Math.min(1.25,target-(b.angle-a.angle))),speed=b.angularVelocity-a.angularVelocity,torque=Math.max(-power,Math.min(power,e*power-speed*power*this.params.jointDamping*5));a.torque-=torque;b.torque+=torque}
 beforeUpdate(){const b=this.bodies,k=this.keys;this.limits.forEach(([a,c,min,max])=>{let r=c.angle-a.angle;if(r<min)this.drive(a,c,min,.006);if(r>max)this.drive(a,c,max,.006)});this.drive(b.leftShin,b.leftFoot,.02,.0018);this.drive(b.rightShin,b.rightFoot,.02,.0018);if(!k.q&&!k.w){this.drive(b.torso,b.leftThigh,.13,.01);this.drive(b.torso,b.rightThigh,-.16,.01)}if(!k.o&&!k.p){this.drive(b.leftThigh,b.leftShin,-.02,.007);this.drive(b.rightThigh,b.rightShin,.04,.007)}if(k.q){this.drive(b.torso,b.rightThigh,-.92,this.params.hipTorque);this.drive(b.torso,b.leftThigh,.62,this.params.hipTorque*.82)}if(k.w){this.drive(b.torso,b.leftThigh,-.92,this.params.hipTorque);this.drive(b.torso,b.rightThigh,.62,this.params.hipTorque*.82)}if(k.o){this.drive(b.rightThigh,b.rightShin,-1.35,this.params.kneeTorque);this.drive(b.leftThigh,b.leftShin,.12,this.params.kneeTorque*.74)}if(k.p){this.drive(b.leftThigh,b.leftShin,-1.35,this.params.kneeTorque);this.drive(b.rightThigh,b.rightShin,.12,this.params.kneeTorque*.74)}let e=-.035-b.torso.angle;b.torso.torque+=Math.max(-this.params.postureTorque,Math.min(this.params.postureTorque,e*this.params.postureTorque-b.torso.angularVelocity*this.params.postureTorque*1.4));b.head.torque+=(-b.head.angle-b.head.angularVelocity*.8)*this.params.postureTorque*.22}
 step(dt){Engine.update(this.engine,Math.min(dt,33.333))}
 get distance(){return(this.bodies.torso.position.x-this.startX)/72}
}
window.QWOPPhysics={RunnerPhysics,DEFAULTS,SCALE:72}})();
