import { SCENARIOS } from "./debug-scenarios.js";
const group=(title,body)=>`<details open><summary>${title}</summary><div class="debug-group">${body}</div></details>`;
export function mountDebugUI(actions){
  document.body.insertAdjacentHTML("beforeend",`<div id="debugBadge">DEBUG MODE</div><button id="debugToggle" aria-controls="debugPanel">DEBUG</button><aside id="debugPanel"><header><b>DEBUG CONTROL</b><button data-debug="close">×</button></header><div class="debug-scroll">
  ${group("プレイヤー",`<div class="debug-grid"><button data-debug="add-criminal">CPU犯人を追加</button><button data-debug="add-detective">CPU刑事を追加</button><button data-debug="add-any">CPUを1人追加</button><button data-debug="fill">必要人数まで補充</button><button data-debug="delete-bots">CPU全削除</button><button data-debug="me-criminal">自分を犯人</button><button data-debug="me-detective">自分を刑事</button><button data-debug="reroll">役割を再抽選</button></div><div id="debugBots"></div>`)}
  ${group("仮想GPS",`<label><input id="virtualGps" type="checkbox"> 仮想GPSを使用</label><label>地図タップ <select id="virtualMode"><option value="warp">即時ワープ</option><option value="walk">徒歩 4km/h</option><option value="brisk">早歩き 6km/h</option><option value="run">走行 10km/h</option></select></label><div class="debug-coords"><input id="debugLat" type="number" step=".000001" placeholder="latitude"><input id="debugLng" type="number" step=".000001" placeholder="longitude"><input id="debugAccuracy" type="number" value="5" placeholder="accuracy"></div><button data-debug="set-coords">座標へ移動</button><div class="debug-pad"><button data-bearing="315">↖</button><button data-bearing="0">↑</button><button data-bearing="45">↗</button><button data-bearing="270">←</button><button data-bearing="reset">●</button><button data-bearing="90">→</button><button data-bearing="225">↙</button><button data-bearing="180">↓</button><button data-bearing="135">↘</button></div>`)}
  ${group("目撃情報・偽情報",`<div class="debug-grid"><button data-debug="witness">即時生成</button><button data-debug="witness-exact">正確な情報</button><button data-debug="witness-100">誤差100m</button><button data-debug="witness-300">誤差300m</button><button data-debug="false-witness">偽情報300m</button><button data-debug="clear-witness">全削除</button></div><label><input id="showTruth" type="checkbox" checked> 全員の真の位置を表示</label>`)}
  ${group("捕獲・時間・状態",`<div id="debugCaptureState" class="debug-state">部屋作成後に表示</div><div class="debug-grid"><button data-debug="criminal-5">犯人を5m先へ</button><button data-debug="criminal-out">犯人を距離外へ</button><button data-debug="capture-reset">捕獲リセット</button><button data-debug="detective-win">刑事勝利</button><button data-debug="criminal-win">犯人勝利</button><button data-debug="time-10">残り10秒</button><button data-debug="time-60">残り1分</button><button data-debug="head-end">先行終了</button><button data-debug="phase-lobby">lobby</button><button data-debug="phase-playing">playing</button></div>`)}
  ${group("通信・GPS・安全",`<div class="debug-grid"><button data-debug="me-offline">自分 offline</button><button data-debug="bots-offline">CPU offline</button><button data-debug="gps-old">GPSを古く</button><button data-debug="accuracy-100">accuracy 100m</button><button data-debug="speed-20">速度20km/h</button><button data-debug="safety-warning">安全警告</button></div>`)}
  ${group("シナリオ",`<select id="debugScenario">${SCENARIOS.map(([v,n])=>`<option value="${v}">${n}</option>`).join("")}</select><button data-debug="scenario">シナリオ実行</button>`)}
  ${group("Firebase",`<div class="debug-grid"><button data-debug="copy-json">JSONコピー</button><button data-debug="download-json">JSON保存</button></div><pre id="debugJson">部屋未作成</pre>`)}
  ${group("ログ",`<div class="debug-grid"><button data-debug="copy-log">コピー</button><button data-debug="clear-log">クリア</button><button data-debug="reset-settings">設定初期化</button></div><div id="debugLog"></div>`)}
  </div></aside>`);
  const panel=document.querySelector("#debugPanel"),saved=JSON.parse(localStorage.getItem("gps-debug-settings")||"{}");panel.classList.toggle("open",saved.open!==false);
  document.querySelector("#debugToggle").onclick=()=>{panel.classList.toggle("open");actions.setting("open",panel.classList.contains("open"))};
  panel.addEventListener("click",e=>{const cmd=e.target.dataset.debug,b=e.target.dataset.bearing;if(cmd)actions.command(cmd);if(b)actions.nudge(b)});
  document.querySelector("#virtualGps").onchange=e=>actions.virtual(e.target.checked);document.querySelector("#virtualMode").onchange=e=>actions.setting("moveMode",e.target.value);document.querySelector("#showTruth").onchange=e=>actions.truth(e.target.checked);
  return {panel,bots:document.querySelector("#debugBots"),json:document.querySelector("#debugJson"),log:document.querySelector("#debugLog"),capture:document.querySelector("#debugCaptureState")};
}
