import { pathRef, update, push, remove } from "./firebase-service.js";
import { makeWitness } from "./witness.js";
import { distanceMeters } from "./utils.js";
import { makeBot, nextBotPosition, destination } from "./debug-bots.js";
import { VirtualGPS } from "./debug-gps.js";
import { mountDebugUI } from "./debug-ui.js";

const STORE="gps-debug-settings";
export function initDebug(ctx){
  let settings={moveMode:"warp",showTruth:true,...JSON.parse(localStorage.getItem(STORE)||"{}")},logs=[],ui;
  const virtual=new VirtualGPS(p=>{ctx.setPosition(p);log("GPS更新","自分",`仮想位置 ${p.lat.toFixed(6)}, ${p.lng.toFixed(6)}`,p)});
  const save=()=>localStorage.setItem(STORE,JSON.stringify(settings));
  const state=()=>ctx.getState(), room=()=>ctx.getRoom(), me=()=>state()?.players?.[ctx.getUid()];
  function log(type,player,message,extra){logs.unshift({time:new Date().toLocaleTimeString("ja-JP"),type,player,message,extra});logs=logs.slice(0,500);renderLog();}
  async function patch(path,value){if(!room()?.id)return ctx.toast("先に部屋を作成してください");await room().patch(path,value);log("Firebase送信","system",path,value);}
  const origin=()=>ctx.getPosition()||{lat:35.6812,lng:139.7671,accuracy:5,speed:0,heading:0,timestamp:Date.now()};
  async function addBot(role){if(Object.keys(state()?.players||{}).length>=6)return ctx.toast("参加者は6人までです");const bots=Object.values(state()?.players||{}).filter(p=>p.isBot&&p.role==="detective");const [id,bot]=makeBot(role,bots.length,origin());await patch(`players/${id}`,bot);log("CPU追加",bot.displayName,"追加",{id,role});}
  async function deleteBots(){if(!confirm("CPUをすべて削除しますか？"))return;const updates={};Object.entries(state()?.players||{}).filter(([,p])=>p.isBot).forEach(([id])=>updates[`players/${id}`]=null);await update(pathRef(room().id),updates);}
  async function setMyRole(role){const updates={[`players/${ctx.getUid()}/role`]:role};for(const [id,p] of Object.entries(state()?.players||{}))if(id!==ctx.getUid()&&role==="criminal"&&p.role==="criminal")updates[`players/${id}/role`]="detective";await update(pathRef(room().id),updates);log("役割変更",me()?.displayName,role);}
  async function reroll(){const ids=Object.keys(state()?.players||{}),criminal=ids[Math.floor(Math.random()*ids.length)],updates={};ids.forEach(id=>updates[`players/${id}/role`]=id===criminal?"criminal":"detective");await update(pathRef(room().id),updates);}
  function criminalEntry(){return Object.entries(state()?.players||{}).find(([,p])=>p.role==="criminal");}
  async function witness(offset=200,falseInfo=false){const c=criminalEntry()?.[1];if(!c?.position)return ctx.toast("位置を持つ犯人がいません");let report=makeWitness(Date.now(),c.position,null,1);if(offset===0){report.centerLat=c.position.lat;report.centerLng=c.position.lng;report.radius=30;report.message="正確な目撃情報（デバッグ）"}else{const fake=destination(c.position,Math.random()*360,offset);report.centerLat=fake.lat;report.centerLng=fake.lng;report.radius=Math.max(50,offset);report.message=`${falseInfo?"偽":"誤差付き"}目撃情報（約${offset}m）`;report.isDebug=true;report.isFalse=falseInfo;report.sourceLat=c.position.lat;report.sourceLng=c.position.lng;}await push(pathRef(`${room().id}/witnessReports`),report);log("目撃情報生成",c.displayName,report.message,report);}
  async function moveCriminal(meters){const [id,c]=criminalEntry()||[];if(!id)return ctx.toast("犯人がいません");const p=destination(origin(),90,meters);await patch(`players/${id}/position`,{...p,accuracy:5,speed:0,timestamp:Date.now()});}
  async function win(role){if(!confirm(`${role==="detective"?"刑事":"犯人"}勝利を強制しますか？`))return;await patch("game",{...state().game,phase:"finished",winnerRole:role,finishedAt:Date.now(),capturedByUid:role==="detective"?ctx.getUid():null});}
  async function phase(name){const now=Date.now(),game={...state().game,phase:name};if(name==="playing")Object.assign(game,{startedAt:now,headStartEndsAt:now,endsAt:now+(state().settings.durationSeconds||60)*1000});await patch("game",game);}
  async function scenario(name){if(!room()?.id)return ctx.toast("先にデバッグ用の部屋を作成してください");if(!confirm("CPU・目撃情報を初期化してシナリオを実行しますか？"))return;await deleteBotsSafe();await remove(pathRef(`${room().id}/witnessReports`));await remove(pathRef(`${room().id}/captureCandidates`));ctx.resetCapture();
    const base={durationSeconds:60,witnessIntervalSeconds:10,captureDistanceMeters:30,captureHoldSeconds:5,headStartSeconds:0};await patch("settings",{...state().settings,...base});
    if(name==="criminal"){await setMyRole("criminal");await addBot("detective");await addBot("detective");await patch("settings",{...state().settings,durationSeconds:120,headStartSeconds:0});}
    else{await setMyRole("detective");await addBot("criminal");if(name==="multiple"){await addBot("detective");await addBot("detective");}}
    await phase("playing");setTimeout(async()=>{if(name==="capture")await moveCriminal(20);if(name==="badGps"){await moveCriminal(10);const [id]=criminalEntry()||[];if(id)await patch(`players/${id}/position`,{...state().players[id].position,accuracy:100,timestamp:Date.now()});}if(name==="disconnect"){const [id]=criminalEntry()||[];if(id)await patch(`players/${id}`,{isOnline:false,lastSeenAt:Date.now()-70000});}if(name==="falseWitness")await witness(300,true);if(name==="timeout")await patch("game",{...state().game,phase:"playing",headStartEndsAt:Date.now(),endsAt:Date.now()+10000});if(name==="speed")safety(20);},500);log("シナリオ","system",name);}
  async function deleteBotsSafe(){const u={};Object.entries(state()?.players||{}).filter(([,p])=>p.isBot).forEach(([id])=>u[`players/${id}`]=null);if(Object.keys(u).length)await update(pathRef(room().id),u);}
  function safety(kmh){const p={...origin(),speed:kmh/3.6,timestamp:Date.now()};ctx.setPosition(p);ctx.showWarning(kmh>=15?"安全停止：高速移動を検出しました":"速度警告：周囲を確認してください");log("安全警告","自分",`${kmh}km/h`);}
  async function command(cmd){try{const commands={
    "close":()=>ui.panel.classList.remove("open"),"add-criminal":()=>addBot("criminal"),"add-detective":()=>addBot("detective"),"add-any":()=>addBot("detective"),"fill":async()=>{if(Object.keys(state()?.players||{}).length<2)await addBot(me()?.role==="criminal"?"detective":"criminal")},"delete-bots":deleteBots,"me-criminal":()=>setMyRole("criminal"),"me-detective":()=>setMyRole("detective"),"reroll":reroll,
    "set-coords":()=>virtual.set({lat:+document.querySelector("#debugLat").value,lng:+document.querySelector("#debugLng").value,accuracy:+document.querySelector("#debugAccuracy").value||5}),"witness":()=>witness(200),"witness-exact":()=>witness(0),"witness-100":()=>witness(100),"witness-300":()=>witness(300),"false-witness":()=>witness(300,true),"clear-witness":()=>confirm("目撃情報を削除しますか？")&&remove(pathRef(`${room().id}/witnessReports`)),
    "criminal-5":()=>moveCriminal(5),"criminal-out":()=>moveCriminal((state()?.settings?.captureDistanceMeters||25)+30),"capture-reset":ctx.resetCapture,"detective-win":()=>win("detective"),"criminal-win":()=>win("criminal"),"time-10":()=>patch("game",{...state().game,endsAt:Date.now()+10000}),"time-60":()=>patch("game",{...state().game,endsAt:Date.now()+60000}),"head-end":()=>patch("game",{...state().game,headStartEndsAt:Date.now(),phase:"playing"}),"phase-lobby":()=>phase("lobby"),"phase-playing":()=>phase("playing"),
    "me-offline":()=>patch(`players/${ctx.getUid()}`,{isOnline:me()?.isOnline===false,lastSeenAt:Date.now()}),"bots-offline":async()=>{for(const [id,p]of Object.entries(state()?.players||{}))if(p.isBot)await patch(`players/${id}`,{isOnline:false})},"gps-old":()=>ctx.setPosition({...origin(),timestamp:Date.now()-30000}),"accuracy-100":()=>ctx.setPosition({...origin(),accuracy:100,timestamp:Date.now()}),"speed-20":()=>safety(20),"safety-warning":()=>ctx.showWarning("デバッグ：周囲を確認してください"),
    "scenario":()=>scenario(document.querySelector("#debugScenario").value),"copy-json":()=>navigator.clipboard.writeText(JSON.stringify(state(),null,2)),"download-json":()=>download("gps-room-debug.json",JSON.stringify(state(),null,2)),"copy-log":()=>navigator.clipboard.writeText(logs.map(x=>`${x.time} [${x.type}] ${x.player}: ${x.message}`).join("\n")),"clear-log":()=>{logs=[];renderLog()},"reset-settings":()=>{localStorage.removeItem(STORE);location.reload()}}
    ;await commands[cmd]?.();}catch(e){log("エラー","system",e.message);ctx.toast(e.message)}}
  function download(name,text){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"application/json"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
  function renderLog(){if(ui)ui.log.innerHTML=logs.slice(0,100).map(x=>`<div><time>${x.time}</time> <b>${x.type}</b> ${x.player}: ${x.message}</div>`).join("");}
  function render(s){if(!ui)return;ui.json.textContent=s?JSON.stringify({meta:s.meta,settings:s.settings,game:s.game,players:s.players,witnessReports:s.witnessReports,captureCandidates:s.captureCandidates},null,2):"部屋未作成";const bots=Object.entries(s?.players||{}).filter(([,p])=>p.isBot);ui.bots.innerHTML=bots.map(([id,p])=>`<div class="debug-bot"><b>${p.displayName}</b><span>${p.role} / ${p.behavior} / ${p.debugSpeedKmh}km/h / ${p.isOnline===false?"offline":"online"}</span><small>${p.position?`${p.position.lat.toFixed(5)}, ${p.position.lng.toFixed(5)} ±${p.position.accuracy}m`:"位置なし"}</small><button data-debug-delete="${id}">削除</button></div>`).join("")||"<p>CPUなし</p>";ui.bots.querySelectorAll("[data-debug-delete]").forEach(b=>b.onclick=()=>confirm("このCPUを削除しますか？")&&remove(pathRef(`${room().id}/players/${b.dataset.debugDelete}`)));const c=criminalEntry()?.[1],m=me(),d=distanceMeters(m?.position||ctx.getPosition(),c?.position);ui.capture.textContent=`距離: ${Number.isFinite(d)?d.toFixed(1):"--"}m / 捕獲距離: ${s?.settings?.captureDistanceMeters||"--"}m / 自分精度: ${(m?.position||ctx.getPosition())?.accuracy||"--"}m / 犯人精度: ${c?.position?.accuracy||"--"}m`;ctx.showDebugPlayers(settings.showTruth?s?.players:null,s?.settings?.captureDistanceMeters);log("Firebase受信","room","更新");}
  ui=mountDebugUI({command,nudge:b=>b==="reset"?virtual.set(origin()):virtual.nudge(+b),virtual:value=>{settings.virtualGps=value;save();virtual.setEnabled(value,origin());ctx.useVirtual(value)},truth:value=>{settings.showTruth=value;save();ctx.showDebugPlayers(value?state()?.players:null,state()?.settings?.captureDistanceMeters)},setting:(key,value)=>{settings[key]=value;save()}});
  document.querySelector("#virtualGps").checked=!!settings.virtualGps;document.querySelector("#virtualMode").value=settings.moveMode||"warp";document.querySelector("#showTruth").checked=settings.showTruth!==false;virtual.setEnabled(!!settings.virtualGps,origin());ctx.useVirtual(!!settings.virtualGps);
  ctx.onMapClick(latlng=>{if(virtual.enabled)virtual.moveTo(latlng,document.querySelector("#virtualMode").value)});
  const keys={ArrowUp:0,w:0,ArrowRight:90,d:90,ArrowDown:180,s:180,ArrowLeft:270,a:270};addEventListener("keydown",e=>{if(virtual.enabled&&keys[e.key]!==undefined){e.preventDefault();virtual.nudge(keys[e.key])}});
  const cpuTimer=setInterval(async()=>{const s=state();if(!s||!room()?.id)return;const reports=Object.values(s.witnessReports||{}).sort((a,b)=>b.createdAt-a.createdAt);for(const [id,bot]of Object.entries(s.players||{})){if(!bot.isBot)continue;const p=nextBotPosition(bot,s.players,reports[0]);if(p)await room().patch(`players/${id}`,{position:p,lastSeenAt:Date.now()});}},1000);
  return {render,log,dispose:()=>{clearInterval(cpuTimer);virtual.dispose()}};
}
