import { GPS } from "./gps.js"; import { GameMap } from "./map.js"; import { SAFETY_ITEMS,isNameValid } from "./safety.js"; import { makeWitness } from "./witness.js"; import { captureState } from "./capture.js"; import { formatClock,normalizeRoomId } from "./utils.js";
const $=s=>document.querySelector(s), screens=[...document.querySelectorAll(".screen")]; let mode="create",uid,room,data,myPos,map,gps,sendTimer,tickTimer,witnessUnsub=null,captureSince=0,lastWitnessPos=null,roleSeen=false,debugController=null,useVirtualGps=false;
const show=id=>{screens.forEach(x=>x.classList.toggle("active",x.id===id));if(id==="game"){map??=new GameMap("map");map.show();}}; const toast=m=>{const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2300)};
const debugRequestedByUrl=new URLSearchParams(location.search).get("debug")==="1"||globalThis.GPS_CHASE_DEV===true;let debugEnabled=debugRequestedByUrl,debugLoadPromise=null;
let leafletReadyPromise=null;function ensureLeaflet(){if(globalThis.L)return Promise.resolve();if(leafletReadyPromise)return leafletReadyPromise;leafletReadyPromise=new Promise((resolve,reject)=>{let script=$("#leafletScript");const loaded=()=>globalThis.L?resolve():reject(new Error("地図ライブラリを読み込めませんでした"));if(!script){script=document.createElement("script");script.id="leafletScript";script.src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js";script.defer=true;document.head.append(script)}script.addEventListener("load",loaded,{once:true});script.addEventListener("error",()=>reject(new Error("地図ライブラリの通信に失敗しました")),{once:true});if(globalThis.L)resolve()});return leafletReadyPromise}
function enableDebugStyles(){if(document.querySelector('link[href="css/debug.css"]'))return;const link=document.createElement("link");link.rel="stylesheet";link.href="css/debug.css";document.head.append(link)}
function addDebugOption(selector,value,label){const select=$(selector);if(![...select.options].some(option=>option.value===value))select.add(new Option(label,value))}
function removeDebugOptions(){for(const [selector,value]of [["#duration","60"],["#witness","10"],["#headstart","0"]]){const option=[...$(selector).options].find(item=>item.value===value);option?.remove()}}
function resetSessionUI(){lastWitnessPos=null;captureSince=0;$("#witnessCard").hidden=true;$("#capture").hidden=true;$("#warning").hidden=true;map?.witness(null)}
function loadDebug(){debugEnabled=true;enableDebugStyles();addDebugOption("#duration","60","1分（Debug）");addDebugOption("#witness","10","10秒（Debug）");addDebugOption("#headstart","0","なし（Debug）");if(debugController)return Promise.resolve(debugController);if(debugLoadPromise)return debugLoadPromise;debugLoadPromise=ensureLeaflet().then(()=>import("./debug.js")).then(({initDebug})=>{debugController=initDebug({getState:()=>data,getRoom:()=>room,getUid:()=>uid,getPosition:()=>myPos,setPosition:p=>{myPos=p;map?.position(p);if(room?.id&&uid)room.patch(`players/${uid}/position`,p)},useVirtual:v=>{useVirtualGps=v;if(v)gps?.stop();else if(uid&&uid!=="debug_user")gps?.start()},toast,resetCapture:()=>{captureSince=0;$("#capture").hidden=true},showWarning:m=>{$("#warning").hidden=false;$("#warning").textContent=m},onMapClick:cb=>{map??=new GameMap("map");map.onDebugClick(cb)},showDebugPlayers:(players,distance)=>{map??=new GameMap("map");map.debugPlayers(players,distance)}});return debugController}).catch(e=>{debugLoadPromise=null;console.error("Debug initialization failed",e);throw e});return debugLoadPromise}
if(debugEnabled)loadDebug();
document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>{const to=b.dataset.go;if(to==="create"||to==="join"){mode=to;$("#entryTitle").textContent=to==="create"?"部屋を作る":"部屋に参加";$("#roomField").hidden=to!=="join";show("profile")}else show(to)});
$("#localDebugStart").onclick=async()=>{try{await loadDebug();const {LocalRoom}=await import("./local-room.js");gps?.stop();clearInterval(sendTimer);clearInterval(tickTimer);witnessUnsub?.();witnessUnsub=null;await room?.leave();resetSessionUI();uid="debug_user";myPos={lat:35.6812,lng:139.7671,accuracy:5,speed:0,heading:0,timestamp:Date.now()};room=new LocalRoom(uid,renderRoom);roleSeen=false;await room.create("デバッグプレイヤー");await debugController.activateLocalMode();show("lobby");toast("ローカルデバッグを開始しました")}catch(e){toast(`デバッグ開始失敗: ${e.message}`)}};
$("#safetyItems").innerHTML=SAFETY_ITEMS.map(x=>`<p>✓ ${x}</p>`).join(""); $("#agree").onchange=e=>$("#gpsStart").disabled=!e.target.checked; $("#roomId").oninput=e=>e.target.value=normalizeRoomId(e.target.value);
$("[data-modal=how]").onclick=()=>$("#how").showModal();$(".dialog-close").onclick=()=>$("#how").close();
$("#toSafety").onclick=()=>{if(!isNameValid($("#name").value))return toast("表示名を1〜12文字で入力してください");if(mode==="join"&&$("#roomId").value.length!==6)return toast("6桁の部屋IDを入力してください");show("safety")};
const gpsStatus=(m,state)=>{$("#gpsStatus").textContent=m;if(room?.id)room.patch(`players/${uid}`,{gpsStatus:m}).catch(()=>{})};
$("#gpsStart").onclick=async()=>{try{const [{authenticate},{Room}]=await Promise.all([import("./firebase-service.js"),import("./room.js")]);uid=(await authenticate()).uid;gps??=new GPS((p,s)=>{if(useVirtualGps)return;myPos=p;map?.position(p);$("#warning").hidden=!s.warning;$("#warning").textContent=s.stopped?"安全停止：乗り物から降り、安全な場所で停止してください":"速度が高いようです。周囲を確認してください"},gpsStatus);if(!useVirtualGps)gps.start();room=new Room(uid,renderRoom);if(mode==="create")await room.create($("#name").value.trim());else await room.join($("#roomId").value,$("#name").value.trim());show("lobby")}catch(e){toast(e.message)}};
function renderRoom(next){if(!next){data=null;toast("部屋が終了しました");show("home");return}data=next;debugController?.render(data);const me=data.players?.[uid];if(!me)return;$("#roomCode").textContent=room.isLocal?"LOCAL TEST":room.id;$("#copyRoom").hidden=!!room.isLocal;const settingValues={duration:data.settings?.durationSeconds,witness:data.settings?.witnessIntervalSeconds,distance:data.settings?.captureDistanceMeters,headstart:data.settings?.headStartSeconds,roles:data.settings?.roleAssignmentMode};for(const [id,value]of Object.entries(settingValues)){const select=$(`#${id}`);if([...select.options].some(option=>option.value===String(value)))select.value=String(value)}const list=Object.entries(data.players||{});$("#count").textContent=`${list.length} / 6`;$("#players").innerHTML=list.map(([id,p])=>`<div class="player"><b>${escapeHtml(p.displayName)}${p.isBot?" 🤖":""}${id===data.meta.hostUid?" ★":""}</b><small>${p.role?roleLabel(p.role):"役割未定"}・${p.isReady?"準備OK":"準備中"}・${p.isOnline===false?"切断":"接続中"}</small></div>`).join("");const host=data.meta.hostUid===uid;$("#settings").style.opacity=host?1:.65;$("#settings").querySelectorAll("select").forEach(x=>x.disabled=!host);$("#start").hidden=!host;$("#start").disabled=list.length<2||!list.every(([,p])=>p.isReady);$("#ready").textContent=me.isReady?"準備を取り消す":"準備完了";if($("#game").classList.contains("active")){$("#roleBadge").textContent=roleLabel(me.role);$("#roleBadge").style.color=me.role==="criminal"?"var(--red)":"var(--blue)"}
 if(data.game?.phase==="headstart"||data.game?.phase==="playing"){if(!roleSeen){roleSeen=true;$("#roleName").textContent=roleLabel(me.role);$("#roleName").style.color=me.role==="criminal"?"var(--red)":"var(--blue)";$("#roleHelp").textContent=me.role==="criminal"?"制限時間まで逃げ切ってください。刑事の位置は表示されません。":"目撃情報を手掛かりに犯人を追跡してください。";show("role")}}
 if(data.game?.phase==="finished"){clearInterval(sendTimer);clearInterval(tickTimer);witnessUnsub?.();witnessUnsub=null;gps?.stop();$("#winner").textContent=data.game.winnerRole==="criminal"?"犯人の勝利":"刑事の勝利";const capturer=data.players?.[data.game.capturedByUid]?.displayName;$("#resultText").textContent=capturer?`${capturer} が犯人を捕獲しました。`:"犯人が制限時間まで逃げ切りました。";show("result")}}
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const roleLabel=r=>r==="criminal"?"犯人":"刑事";
$("#copyRoom").onclick=()=>navigator.clipboard.writeText(room.id).then(()=>toast("部屋IDをコピーしました"));$("#ready").onclick=()=>room.ready(!data.players[uid].isReady);$("#leave").onclick=leave;$("#resultLeave").onclick=leave;async function leave(){const wasLocal=!!room?.isLocal;gps?.stop();clearInterval(sendTimer);clearInterval(tickTimer);witnessUnsub?.();witnessUnsub=null;await room?.leave();data=null;room=null;debugController?.render(null);resetSessionUI();if(wasLocal){debugController?.deactivateLocalMode(!debugRequestedByUrl);myPos=null;uid=null;map?.clearPosition();if(!debugRequestedByUrl){debugEnabled=false;removeDebugOptions()}}show("home")}
document.querySelectorAll("#settings select").forEach(x=>x.onchange=()=>room.patch("settings",{durationSeconds:+$("#duration").value,witnessIntervalSeconds:+$("#witness").value,captureDistanceMeters:+$("#distance").value,headStartSeconds:+$("#headstart").value,roleAssignmentMode:$("#roles").value}));
$("#start").onclick=async()=>{const ids=Object.keys(data.players),assigned=debugEnabled?ids.find(id=>data.players[id].role==="criminal"):null,criminal=assigned||(data.settings.roleAssignmentMode==="manual"?uid:ids[Math.floor(Math.random()*ids.length)]),now=Date.now(),updates={};ids.forEach(id=>updates[`players/${id}/role`]=id===criminal?"criminal":"detective");updates["meta/status"]="playing";updates["game"]={phase:"headstart",startedAt:now,headStartEndsAt:now+data.settings.headStartSeconds*1000,endsAt:now+(data.settings.headStartSeconds+data.settings.durationSeconds)*1000,generationId:0};await room.bulkPatch(updates)};
$("#roleOk").onclick=enterGame;async function enterGame(){await ensureLeaflet();show("game");const me=data.players[uid];$("#roleBadge").textContent=roleLabel(me.role);$("#roleBadge").style.color=me.role==="criminal"?"var(--red)":"var(--blue)";if(myPos)map.position(myPos);clearInterval(sendTimer);sendTimer=setInterval(()=>{if(myPos)room.patch(`players/${uid}/position`,myPos)},(data.settings.positionSendIntervalSeconds||5)*1000);tick() ;clearInterval(tickTimer);tickTimer=setInterval(tick,1000);witnessUnsub?.();witnessUnsub=room.subscribeWitness(value=>{const reports=Object.values(value||{}).sort((a,b)=>b.createdAt-a.createdAt);if(!reports[0]){$("#witnessCard").hidden=true;map.witness(null);return}if(data.players?.[uid]?.role==="detective"){$("#witnessText").textContent=reports[0].message;$("#witnessCard").hidden=false;map.witness(reports[0])}})}
async function tick(){if(!data?.game)return;const now=Date.now(),me=data.players[uid],head=Math.max(0,Math.ceil((data.game.headStartEndsAt-now)/1000)),remaining=Math.max(0,Math.ceil((data.game.endsAt-now)/1000));$("#timer").textContent=head?`先行 ${head}`:formatClock(remaining);const interval=data.settings.witnessIntervalSeconds,elapsed=Math.max(0,Math.floor((now-data.game.headStartEndsAt)/1000));$("#nextWitness").textContent=head?"待機中":`${interval-(elapsed%interval)}秒`;
 if(data.game.phase==="headstart"&&now>=data.game.headStartEndsAt&&data.meta.hostUid===uid)await room.patch("game",{phase:"playing"});if(remaining<=0&&["headstart","playing"].includes(data.game.phase)&&data.meta.hostUid===uid)await finish("criminal");
 if(data.game.phase==="playing"&&data.meta.hostUid===uid&&elapsed>0&&elapsed%interval===0&&data.game.generationId!==Math.floor(elapsed/interval)){const criminal=Object.values(data.players).find(p=>p.role==="criminal");if(criminal?.position){const report=makeWitness(now,criminal.position,lastWitnessPos,Math.min(3,1+Math.floor(elapsed/(interval*3))));lastWitnessPos=criminal.position;await room.addWitness(report);await room.patch("game",{generationId:Math.floor(elapsed/interval)})}}
 if(me.role==="detective"&&data.game.phase==="playing"){const criminal=Object.values(data.players).find(p=>p.role==="criminal"),state=captureState(myPos,criminal?.position,data.settings,captureSince,now);if(state.valid&&!captureSince)captureSince=now;if(!state.valid)captureSince=0;$("#capture").hidden=!state.valid;$("#capture").textContent=`接近中 ${Math.floor(state.progress*data.settings.captureHoldSeconds)} / ${data.settings.captureHoldSeconds}秒`;if(state.progress>=1)await room.transactionGame(g=>g?.phase==="playing"?{...g,phase:"finished",winnerRole:"detective",capturedByUid:uid,capturedAt:Date.now()}:undefined)}}
async function finish(winner){await room.transactionGame(g=>g?.phase!=="finished"?{...g,phase:"finished",winnerRole:winner,finishedAt:Date.now()}:undefined)}
$("#locate").onclick=()=>map.center(myPos);$("#fold").onclick=()=>$("#details").hidden=!$("#details").hidden;$("#rematch").onclick=async()=>{roleSeen=false;clearInterval(tickTimer);witnessUnsub?.();witnessUnsub=null;resetSessionUI();await room.removeNode("witnessReports");await room.removeNode("captureCandidates");await room.patch("game",{phase:"lobby",generationId:0,startedAt:null,headStartEndsAt:null,endsAt:null,winnerRole:null,capturedByUid:null,capturedAt:null,finishedAt:null});await room.patch("meta",{status:"lobby"});const entries=Object.entries(data.players),firstBotId=entries.find(([,player])=>player.isBot)?.[0];for(const [id] of entries){const localRole=room.isLocal?(id===firstBotId?"criminal":"detective"):"";await room.patch(`players/${id}`,{isReady:!!room.isLocal,role:localRole,...(room.isLocal?{}:{position:null})})}show("lobby")};
document.addEventListener("visibilitychange",()=>{if(!document.hidden){gpsStatus("再確認中");toast("復帰しました。GPSと通信を再確認します")}});window.addEventListener("pagehide",()=>gps?.stop());show("home");
